### ISSUE TITLE
AppEngineClientConnection.flush() swallows exceptions generated by App Engine's URLFetchService.fetch(...)

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#101]
Exception swallowing makes it difficult to troubleshoot any API errors in the App Engine environment.

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/AppEngineClientConnection.java#L206

Could wrap the exception instead, e.g.

throw new IOException("Error flushing content in Google App Engine fetch", ex);

**Comment by jingming** [comment]
In version `7.0.0` we have restructured the library so that you can inject your own HTTP Client. If you wish to configure the client differently, you can pass in your own `HttpClient` into the `TwilioRestClient`.
