### ISSUE TITLE
AppEngineClientConnection uses default URLFetchService timeout of 5 seconds, which is too short

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#102]
AppEngineClientConnection.java relies on the default URLFetchService timeout, which is 5 seconds as documented here:

https://developers.google.com/appengine/docs/java/urlfetch/#Java_Making_requests

This is too short since the API server-side timeout is ~30 seconds (client should be longer).

**Comment by jingming** [comment]
In version `7.0.0` we have restructured the library so that you can inject your own HTTP Client. If you wish to configure the client differently, you can pass in your own `HttpClient` into the `TwilioRestClient`.

**Comment by MikeGratsas** [comment]
The classes AppEngineClientConnection and AppEngineClientConnectionManager are not implemented in the latest twilio-java version 7
