### ISSUE TITLE
Verbs don't escape the body for XML embedding

### ISSUE THREAD

**Issue by MBCook** [twilio/twilio-java#110]
I'm trying to reply to incoming SMS messages, and I'm using the SMS verb.

The constructor for SMS passes the body directly to the body field in the Verb base class. The toXML() on the base Verb class looks like this:

```
public String toXML(){
        String xml = "<" + this.tag;

        for (String key : attributes.keySet()) {
            xml += " " + key + "=\"" + attributes.get(key) + "\"";
        }

        xml += ">";

        if(this.body != null)
            xml += this.body;

        for (Verb child : children){
            xml += child.toXML();
        }

        return xml += "</" + this.tag + ">";
}
```

This doesn't escape the body element at all. Here is a simple test case:

```
TwiMLResponse twiml = new TwiMLResponse();

Sms sms = new Sms("I enjoy peanut butter & jelly");

twiml.append(sms);

System.out.println(twiml.toXML());
```

That produces the following output:

```
<Response><Sms>I enjoy peanut butter & jelly</Sms></Response>
```

I expected:

```
<Response><Sms>I enjoy peanut butter &amp; jelly</Sms></Response>
```

It's not escaping the string passed it. I think the principal of least surprise would suggest that the string be automatically be escaped. At the least an alternate constructor could be provided which would automatically escape the content.

**Comment by MikeGratsas** [comment]
The method Verb.toEscapedXML() is missing in TwiML class in the latest twilio-java version 7
