### ISSUE TITLE
mms_outbound_shortcode

### ISSUE THREAD

**Issue by amcconnell** [twilio/twilio-java#136]
I'm getting the following error using both 3.4.1 and 3.4.2 of the twilio-java client.

com.amazonaws.services.simpleworkflow.flow.ActivityFailureException: No enum constant com.twilio.sdk.resource.instance.UsageCategory.mms_outbound_shortcode

There's no documentation for this usage category either.

**Comment by jingming** [comment]
If you are still seeing this issue, please direct it to help@twilio.com
