### ISSUE TITLE
 how to fix Error for The method create(Map<String,String>) in the type SmsFactory is not applicable for the arguments (List<NameValuePair>) #142 

### ISSUE THREAD

**Issue by anilthakur** [twilio/twilio-java#143]
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.TwilioRestException;
import com.twilio.sdk.TwilioRestResponse;
import com.twilio.sdk.resource.factory.SmsFactory;
import com.twilio.sdk.resource.instance.Account;
import com.twilio.sdk.resource.instance.Sms;
import com.twilio.sdk.verbs.TwiMLException;

public class test {

public static final String ACCOUNT_SID = "ACadd3c0c979ef140e795d020dc875d12b";
public static final String AUTH_TOKEN = "4dc309629b3e309c1fb1eb8f376ad490";

public static void main(final String[] args) throws TwilioRestException,
        TwiMLException {

```
 TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN);
// Build a filter for the SmsList
List<NameValuePair> params = new ArrayList<NameValuePair>();
params.add(new BasicNameValuePair("Body", "Jenny please?! I love you <3"));
params.add(new BasicNameValuePair("To", "+14159352345"));
params.add(new BasicNameValuePair("From", "+14158141829"));
SmsFactory smsFactory = client.getAccount().getSmsFactory();
Sms sms = smsFactory.create(params);
System.out.println(sms.getSid());
}
}
```

This code i have written for sending message from my account number to Other number Phone But am getting Error : The method create(Map) in the type SmsFactory is not applicable for the arguments (List) But in Official Document of Twilio Docs its written same code i dont know what am doing mistake .

**Comment by pujacs** [comment]
i took your code , did all modification as u suggested. Still i am getting error in code 
"no suitable constructor found for TreeMap(String,String)"

**Comment by ialuj** [comment]
Guys... How to get Twilio Json Object sent as response from callback?

**Comment by childish-sambino** [comment]
@ialuj Please open a new issue as closed issues are not tracked as closely.
