### ISSUE TITLE
android_twilio

### ISSUE THREAD

**Issue by gurjeet734** [twilio/twilio-java#154]
I m unable to use this twilio-java library in my android app. 
Can any body help me in this .
I m not able to send the message from twilio_android app.

Its giving NoSuchMethodFound error. 
If , I am using the following code in onclick
TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN);
 
    // Build a filter for the MessageList
    List<NameValuePair> params = new ArrayList<NameValuePair>();
    params.add(new BasicNameValuePair("Body", "Jenny please?! I love you <3"));
    params.add(new BasicNameValuePair("To", "+15558675309"));
    params.add(new BasicNameValuePair("From", "+14158141829"));
    params.add(new BasicNameValuePair("MediaUrl", "http://www.example.com/hearts.png"));
     
     
    MessageFactory messageFactory = client.getAccount().getMessageFactory();
    Message message = messageFactory.create(params);
    System.out.println(message.getSid());

please help me...

**Comment by patcon** [comment]
This repo uses the standard apache http-client, and android has an old fork that is specific to android. You'll need to somehow get https://code.google.com/p/httpclientandroidlib/ working (not sure how myself), or search for the twilio android sdk beta, which has another client lib you can use.

I think this issue can be closed, as usage of this library on android is not its intended use
