### ISSUE TITLE
.getStartDate/.getEndDate fails to parse date correctly.

### ISSUE THREAD

**Issue by vincentjames501** [twilio/twilio-java#157]
When getting back a ```UsageRecord``` object, calling ```.getStartDate()``` results in ```null``` being returned because the ```StartDate``` property, at least from my testing, comes back as yyyy-MM-dd and not the expected ```"EEE, dd MMM yyyy HH:mm:ss Z"``` as the code would make it seem:

```java
	public Date getStartDate() {
		SimpleDateFormat format = new SimpleDateFormat(
				"EEE, dd MMM yyyy HH:mm:ss Z");
		try {
			return format.parse(this.getProperty("StartDate"));
		} catch (ParseException e) {
			return null;
		}
	}
```

It looks like we should copy the way that ```FeedbackSummary.java``` is doing this:

```java
    private static final String DATE_FORMAT = "yyyy-MM-dd";
    public static final String START_DATE_PROPERTY = "start_date";
    public Date getStartDate() {
		SimpleDateFormat format = new SimpleDateFormat(DATE_FORMAT);
		try {
			return format.parse(getProperty(START_DATE_PROPERTY));
		} catch (ParseException e) {
			return null;
		}
	}
```

**Comment by jingming** [comment]
We have added correct date parsing in version 7.1.0.
