### ISSUE TITLE
TwilioRestClient through proxy connection?

### ISSUE THREAD

**Issue by dhackbar** [twilio/twilio-java#162]
I was trying to get some existing code that uses twilio working through a http proxy without success without either modifying the application that's calling twilio or modifying the twiliorestclient itself without any success so I started looking at coding options.   

In our case, changing the calling application would require $$$ from a vendor, while changing the twilio-library and replacing it in our application is relatively free.   So I started experimenting with options, so excuse the hack coding.

I found putting the following changes into TwilioRestClient.java class seems to do the trick and allow the calling application not to have to worry about settings.  Just setting a few java properties would be needed (similar to other proxy aware apps).    I found changing the calling application required calling the getHttpClient in twiliorestclient also worked in a test app i wrote, but putting into the library feels like the cleaner option.

Thoughts or other options?

	public static final String PROXY_HOST = System.getProperty("http.proxyHost");
	public static final String PROXY_PORT_S = System.getProperty("http.proxyPort");
	public static final String PROXY_USERNAME = System.getProperty("http.proxyUser");
	public static final String PROXY_PASSWORD = System.getProperty("http.proxyPassword");

       // replace existing routine with this proxy-aware version 
	public TwilioRestClient(String accountSid, String authToken, String endpoint) {

		validateAccountSid(accountSid);
		validateAuthToken(authToken);

		this.accountSid = accountSid;
		this.authToken = authToken;

		if ((endpoint != null) && (!endpoint.equals(""))) {
			this.endpoint = endpoint;
		}

		// Grab the proper connection manager, based on runtime environment
		ClientConnectionManager mgr = null;
		try {
			Class.forName("com.google.appengine.api.urlfetch.HTTPRequest");
			mgr = new AppEngineClientConnectionManager();
		} catch (ClassNotFoundException e) {
			// Not GAE
			mgr = new ThreadSafeClientConnManager();
			((ThreadSafeClientConnManager) mgr).setDefaultMaxPerRoute(10);
		}

		setHttpclient(new DefaultHttpClient(mgr));
		httpclient.getParams().setParameter("http.protocol.version", HttpVersion.HTTP_1_1);
		httpclient.getParams().setParameter("http.socket.timeout", new Integer(CONNECTION_TIMEOUT));
		httpclient.getParams().setParameter("http.connection.timeout", new Integer(CONNECTION_TIMEOUT));
		httpclient.getParams().setParameter("http.protocol.content-charset", "UTF-8");

		if (PROXY_HOST != null) {
			Integer PROXY_PORT = new Integer(PROXY_PORT_S);
			DefaultHttpClient httpClient = (DefaultHttpClient) this.getHttpClient();
			httpClient.getCredentialsProvider().setCredentials(new AuthScope(PROXY_HOST, PROXY_PORT), new UsernamePasswordCredentials(PROXY_USERNAME, PROXY_PASSWORD));

			List<String> authpref = new ArrayList<String>();
			authpref.add(AuthPolicy.BASIC);
			httpClient.getParams().setParameter(AuthPNames.PROXY_AUTH_PREF, authpref);

			HttpHost proxy = new HttpHost(PROXY_HOST, PROXY_PORT);
			httpClient.getParams().setParameter(ConnRoutePNames.DEFAULT_PROXY, proxy);
			setHttpclient(httpClient);
		}

		this.authAccount = new Account(this);
		this.authAccount.setSid(this.accountSid);
		this.authAccount.setAuthToken(this.authToken);
	}

**Comment by jingming** [comment]
In version `7.0.0` we have restructured the library so that you can inject your own HTTP Client. If you wish to configure the client differently, you can pass in your own `HttpClient` into the `TwilioRestClient`.

**Comment by stirumala76** [comment]
@jingming do you have sample code for proxy using HttpClient into the TwilioRestClient.

**Comment by applegrew** [comment]
@jingming In the comment here you have mentioned that the ability to pass our own `HttpClient` was added in version `7.0.0`. However, I see the `com.twilio.sdk.TwilioClient.setHttpClient(HttpClient)` (ref: https://github.com/twilio/twilio-java/blob/30363b5def5a1075561da8ca226c73872c936f50/src/main/java/com/twilio/sdk/TwilioClient.java#L94) and `com.twilio.sdk.TwilioClient.getHttpClient()` codes in base class of `TwilioRestClient` even in version `4.4.4`. I am confused. Can you please elaborate?
