### ISSUE TITLE
mvn install fails using JDK 8 because of Javadoc 'compilation' failures.

### ISSUE THREAD

**Issue by gkopff** [twilio/twilio-java#165]
For example:

    [ERROR] Exit code: 1 - twilio-java/src/main/java/com/twilio/sdk/TwilioRestClient.java:361: error: self-closing element not allowed
    [ERROR] * <p/>
    [ERROR] ^

**Comment by jingming** [comment]
This errant close tag has been removed in `7.0.0`.
