### ISSUE TITLE
Proxy for Twilio Java client

### ISSUE THREAD

**Issue by Nishi** [twilio/twilio-java#166]
Please, support Proxy for Twilio Java client, incl. 
org.apache.http.impl.client.HttpClientBuilder#useSystemProperties() (to pick up "-Dhttp.proxyHost=... -Dhttp.proxyPort=... -Dhttps.proxyHost=... -Dhttps.proxyPort=..." options).

Also, please, upgrade Apache HTTP library to 4.3.6 (org.apache.httpcomponents:httpclient) and 4.3.3 (org.apache.httpcomponents:httpcore).

**Comment by xgp** [comment]
TwilioRestClient allows you to pass in your own HttpClient instance, which you can configure with a proxy:

    HttpClient http = ... //get your client, however your application does (e.g. from a connection manager or new DefaultHttpClient(...)
    if (useProxy) {
        HttpHost proxy = new HttpHost("proxy.example.com", 8080);
        if (useAuth) {
            // if the proxy requires authentication, set a credentials provider
            http.getCredentialsProvider().setCredentials(new AuthScope("proxy.example.com", 8080),
                                                         new UsernamePasswordCredentials("username", "password")));
        }
        http.getParams().setParameter(ConnRoutePNames.DEFAULT_PROXY, proxy);
    }
    TwilioRestClient twilio = new TwilioRestClient("yourAccountSid", "yourAuthToken");
    twilio.setHttpClient(http);
    //use it...

**Comment by jingming** [comment]
Answered.
