### ISSUE TITLE
Queue missing delete()

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#168]
com.twilio.sdk.resource.instance.Queue is missing a delete() method., as described here:

https://www.twilio.com/docs/api/rest/queue#instance-delete

Example Recording.delete():

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/resource/instance/Recording.java#L168

**Comment by jingming** [comment]
This has been added in `7.0.0` here: https://github.com/twilio/twilio-java/blob/twilio-7.0.0/src/main/java/com/twilio/rest/api/v2010/account/Queue.java#L89
