### ISSUE TITLE
messageFactory.create(messageParams); is shows some error?

### ISSUE THREAD

**Issue by TechHanumanInfo** [twilio/twilio-java#171]
I had used same code but at messageFactory.create(messageParams); is shows some error like

"The method create(Map<String,String>) in the type SmsFactory is not applicable for the arguments (List<BasicNameValuePair>)"

so how to create Map object instead of List? please tell me solution for this problem

**Comment by mplacona** [comment]
The argument expected is of type `List`, so you can simply convert your `Map` into a `List`.

Say you had:

`Map<Key,Value> map;`

Just do:

`List<Value> list = new ArrayList<Value>(map.values());`

**Comment by TechHanumanInfo** [comment]
In that example they are given   "final List<NameValuePair> messageParams = new ArrayList<BasicNameValuePair>();" they are created list 

But i want the List as a Map type(Reverse Process).If i will convert List to Map then i have to pass some keys for the List items.So how i will convert List<NameValuePair> into Map object?

"messageFactory.create(messageParams);" this method takes parameter as a Map object type.So i want to convert List to Map.

**Comment by mplacona** [comment]
Would you be able to send me some of your code? I'm struggling to find the example you're talking about, or why you're trying to do it this way.

**Comment by TechHanumanInfo** [comment]
ok i will send,this is the code i am using

final SmsFactory messageFactory = mainAccount.getSmsFactory();
final List<BasicNameValuePair> messageParams = new ArrayList<BasicNameValuePair>();
messageParams.add(new BasicNameValuePair("To", "5105551212")); 
messageParams.add(new BasicNameValuePair("From", "(510) 555-1212")); 
messageParams.add(new BasicNameValuePair("Body","This is a test message!"));

"messageFactory.create(messageParams);"

//At lastline only it is Showing error "The method create(Map) in   the type SmsFactory is not applicable for the arguments (List)"

**Comment by mplacona** [comment]
That example uses `import org.apache.http.message.BasicNameValuePair;` and you need to make sure you have imported it.

If you want to use a map, it's absolutely fine, and this is how you would do it:

`final SmsFactory messageFactory = mainAccount.getSmsFactory();
final Map<String, String> messageParams = new HashMap<String, String>();
messageParams.put("To", "+447590566866");
messageParams.put("From", "+441753463238");
messageParams.put("Body", "This is my message");
messageFactory.create(messageParams);`

Now you are passing a map, and your SMS will be sent.

Let me know if that works for you

**Comment by TechHanumanInfo** [comment]
Thank you error was gone. and i will check that sms is send or not.
