### ISSUE TITLE
How to call the Twilio java class into my android application?

### ISSUE THREAD

**Issue by TechHanumanInfo** [twilio/twilio-java#172]
In my android application i have created one button when i had pressed on the button i want to send message.So for that i have created on java class and written twilio code.But in java class i have created main method. Here is my Java code main method.

//TwilioTest java class
public static void main(final String[] args) throws TwilioRestException,
			TwiMLException {

		// Create a rest client
		final TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID,
				AUTH_TOKEN);

		// Get the main account (The one we used to authenticate the client)
		final Account mainAccount = client.getAccount();

		final SmsFactory messageFactory = mainAccount.getSmsFactory();
		final Map<String, String> messageParams = new HashMap<String, String>();
		messageParams.put("To", "+91123321232");
		messageParams.put("From", "+132432343425");
		messageParams.put("Body", "This is my message");
		messageFactory.create(messageParams);
	}

In my MainActivity 

sms.setOnClickListener(new OnClickListener() {

			@Override
			public void onClick(View v) {
				new TwilioTest();
			}
}
Then it showing this text without sending sms
"D/dalvikvm(14766): DexOpt: unable to opt direct call 0x2452 at 0x0d in Lcom/example/simplesmstest/TwilioTest;.main"

**Comment by TechHanumanInfo** [comment]
Anybody please tell me how to use twilio in my android application,if i am using the above code it showing some error like " java.lang.NoSuchMethodError: org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>"

i have added only one jar file in lib folder as " twilio-java-sdk-3.3.10-jar-with-dependencies.jar ".

please tell me what can i do?

**Comment by TechHanumanInfo** [comment]
I have used direct Http Post method to send sms and i have given parameters like  twilio authentication id and message parameters

**Comment by patcon** [comment]
This library is not designed to work with the android fork of appachehttpclient that comes stock with android. Search google for twilio's android sdk (i think it's in beta)
