### ISSUE TITLE
How to send SMS using Twilio in my android application?

### ISSUE THREAD

**Issue by TechHanumanInfo** [twilio/twilio-java#173]
In my android application i have created one button when i had pressed on the button i want to send message.So for that i have created one java class and written twilio code.

final TwilioRestClient client = new TwilioRestClient(
                        ACCOUNT_SID, AUTH_TOKEN);
                // Get the main account (The one we used to authenticate the
                // client)
                final Account mainAccount = client.getAccount();

                final SmsFactory messageFactory = mainAccount.getSmsFactory();
                final Map<String, String> messageParams = new HashMap<String, String>();
                messageParams.put("To", "+912342423423");
                messageParams.put("From", "+132432432434");
                messageParams.put("Body", "This is my message");
                try {
                    messageFactory.create(messageParams);
                } catch (TwilioRestException e) {
                    e.printStackTrace();
                }
when i am using the above code it showing some error like  java.lang.NoSuchMethodError: org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager

i have added only one jar file in lib folder as " twilio-java-sdk-3.3.10-jar-with-dependencies.jar ".
	
If i have added those "httpcore or httpclient jar" files then it is showing the error is "Multiple dex files define Lorg/apache/http/ConnectionClosedException;" means same classes or same packages are avialble in twilio-sdk-java jar file.So it is showing duplicate classes is available.

please tell me what can i do?

**Comment by panchenko** [comment]
Android has some old version of httpclient embedded which is a little bit different, that's why "NoSuchMethodError".
If you need it to work this way, twilio-java should be manually recompiled (modifying if needed) against Adnroid SDK or https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html.

However, having the twilio credentials in android app does not sound secure - it is possible to decompile it and extract them, IMHO, it would be better sending SMS from your server.

**Comment by TechHanumanInfo** [comment]
Please send me some code how to send sms to server, i am not created any server i have created one activity in that i have called SmsFactory to send sms,is there any files to required to send sms using twilio in Android application?

What can i do now, i am very confusing with this please tell me?

**Comment by TechHanumanInfo** [comment]
I have used direct Http Post method to send sms and i have given parameters like twilio authentication id and message parameters without any libraries.

**Comment by tigerfarm** [comment]
I wrote a Twilio SMS Android  app:
https://github.com/tigerfarm/OwlMessaging
For HTTPS calls, I used OkHttp. Sample use:
https://github.com/tigerfarm/OwlMessaging/blob/master/app/src/main/java/com/tigerfarmpress/owlsms/MainActivity.java
