### ISSUE TITLE
UsageTriggerList.create() fails with nullpointerexception

### ISSUE THREAD

**Issue by na1ya** [twilio/twilio-java#175]
Is:
return makeNew(this.getClient(), (Map<String, Object>) response.toMap().get("UsageTrigger"));

Should be:
return makeNew(this.getClient(), (Map<String, Object>) response.toMap().get("UsageTriggers"));

Tested on sub accounts. Maybe UsageTrigger is returned for the master account.

&lt;TwilioResponse&gt;&lt;UsageTriggers&gt;&lt;Sid&gt;####&lt;/Sid&gt;&lt;AccountSid&gt;####&lt;/AccountSid&gt;&lt;DateCreated&gt;Sat, 14 Feb 2015 16:08:22 +0000&lt;/DateCreated&gt;&lt;DateUpdated&gt;Sat, 14 Feb 2015 16:08:22 +0000&lt;/DateUpdated&gt;&lt;DateFired/&gt;&lt;FriendlyName&gt;Trigger for totalprice at usage of 0.00001&lt;/FriendlyName&gt;&lt;UsageCategory&gt;totalprice&lt;/UsageCategory&gt;&lt;TriggerBy&gt;usage&lt;/TriggerBy&gt;&lt;Recurring&gt;&lt;/Recurring&gt;&lt;TriggerValue&gt;0.00001&lt;/TriggerValue&gt;&lt;CurrentValue&gt;1.6025&lt;/CurrentValue&gt;&lt;CallbackUrl&gt;######&lt;/CallbackUrl&gt;&lt;CallbackMethod&gt;GET&lt;/CallbackMethod&gt;&lt;UsageRecordUri&gt;/2010-04-01/Accounts/#####/Usage/Records?Category=totalprice&lt;/UsageRecordUri&gt;&lt;Uri&gt;/2010-04-01/Accounts/#####/Usage/Triggers/#####&lt;/Uri&gt;&lt;ApiVersion&gt;2010-04-01&lt;/ApiVersion&gt;&lt;/UsageTriggers&gt;&lt;/TwilioResponse&gt;

**Comment by jingming** [comment]
@na1ya We have just released a new version of the helper library `7.0.0` that resolves this issue.
