### ISSUE TITLE
Example on the main page not working as it uses "http://api.twilio.com"

### ISSUE THREAD

**Issue by Zenil** [twilio/twilio-java#179]
When I run the example on the main page, it errors out as the response got from the twilio server is 

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

Checking the example code I see that it uses TwilioRestClient which has :
public TwilioRestClient(final String accountSid, final String authToken) {
		super(accountSid, authToken, "http://api.twilio.com");
...

Its hardcoding http://api.twilio.com, it should be https

**Comment by skimbrel** [comment]
Fixed on master, doing a point release momentarily.
