### ISSUE TITLE
Make Conference.setBeep() API compatible with older implementations

### ISSUE THREAD

**Issue by 4np** [twilio/twilio-java#181]
For an older version of our Twilio implementation we use Twilio SDK 3.4.2 while we are currently prototyping a new iteration using Twilio SDK 3.7.1. We ran tests to determine if our previous implementation would be compatible with SDK 3.7.1, however we are experiencing issues with ```Conference -> setBeep``` which takes a ```String``` in SDK 3.7.1. while it accepted a ```Boolean``` in SDK 3.4.2. This SDK change was introduced in bbb3df0e801f254ce9fd6615d6860e86c36235ea.

As the rest is working as expected, we would very much like to see the ```setBeep``` method also to keep working as expected so we do not need to backport changes to multiple product Versions and Patch Versions, which might have a big customer impact.

Hence the request to add support for the legacy call in the next version of the SDK, something like:

```java
    /**
     * Sets the beep behavior.
     * <ul>
     * <li>"true" - beep on enter and exit</li>
     * <li>"false" - no beep</li>
     * <li>"onEnter" - beep on enter</li>
     * <li>"onExit" - beep on exit</li>
     * </ul>
     *
     * @param value the new beep behavior
     */
    public void setBeep(String value){
        this.set("beep",value);
    }

    /**
     * Sets the beep (legacy behavior)
     * 
     * @param bool  Boolean
     */
    public void setBeep(Boolean bool) {
        this.set("beep", bool.toString());
    }
```

**Comment by 4np** [comment]
I just added the legacy behavior in the pull request above...

**Comment by skimbrel** [comment]
3.7.2 is now available with the override method.
