### ISSUE TITLE
IncomingPhoneNumber only returns high level capabilities but lacks detailed capability information

### ISSUE THREAD

**Issue by 4np** [twilio/twilio-java#187]
Getting the capabilities of a ```IncomingPhoneNumber``` only returns whether or not that incoming phone number supports ```sms```, ```mms``` or ```voice```. Unfortunately many international numbers are more restrictive and while they _do_ support for example SMS, they support it to _local numbers only_. Currently the Java SDK does not properly return the complete capability information.

Example:
```java
IncomingPhoneNumber number = ...

// get capabilities
HashMap<String, Boolean> capabilities = (HashMap<String, Boolean>) number.getObject("capabilities");
```

for a UK based incoming phone number will have the ```capabilities``` HashMap contain the following data:

```java
{voice=true, sms=true, mms=false}
```

But this is not enough information, as this UK number _only_ supports SMS to local numbers. So perhaps it should be returning something like:

```java
{voice="all", sms="local-only", mms="none"}
```

_ps. as we have already code relying on the ```getObject("capabilities")``` logic, please make sure you keep the SDK backward compatible. Perhaps a (currently non-existant) ```getCapabilities``` API call could be added?_

**Comment by ihumanable** [comment]
@4np Thank you for your feedback.  

This information is not currently available in the current API response, it would require that we alter the response of the public API to expose these properties.  Twilio will incorporate your feedback into future feature planning for the API.

**Comment by 4np** [comment]
:+1:

**Comment by jingming** [comment]
Answered.
