### ISSUE TITLE
-Xdoclint:none causing issue

### ISSUE THREAD

**Issue by patcon** [twilio/twilio-java#193]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.280s
[INFO] Finished at: Sat Apr 04 17:21:49 EDT 2015
[INFO] Final Memory: 22M/164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:jar (attach-sources) on project twilio-java-sdk: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-7-openjdk-amd64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/non_encrypted/repos/twilio-java/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Tested with openjdk 1.7 and 1.8 and saw the same error. Removing the line from pom.xml gives success.

(Relatively new to java development, so perhaps it's something obvious, but normalling I just need to run the build command and projects work fine :)

**Comment by skimbrel** [comment]
Is there a particular reason you're running the build yourself? We publish compiled jars to the central repository (http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22twilio-java-sdk%22), so if you set that up as a source for your own projects you should be able to pull it in and use it.

For background, I added this flag a while ago after builds started failing on Oracle JDK 8; it looks like they didn't add the same functionality to the javadoc tool in openjdk. There's probably some voodoo you can do with Maven profiles to make this a conditional property based on which JDK is being invoked. We'd be happy to review/accept a PR for such a change.

**Comment by patcon** [comment]
Heh, I just ran into trouble, so thought I'd let you know :)

I'm likely not doing anything you want to support, but forked the SDK and ported to another service:

https://github.com/patcon/textnow-java-api

Trying to keep it relatively one-for-one, so that I can easily support you guys and those other guys for an app I'm building. So I'll try to push back any clean-up or consistency fixes (I've seen one or two minor things I've been tempted to fix in my fork :)

Thanks for the context. Might've found a good solution elsewhere using profiles, which I'll push if I implement.
