### ISSUE TITLE
Allow delay when building multi-sms messages

### ISSUE THREAD

**Issue by patcon** [twilio/twilio-java#194]
It's likely the fault of my provider, but I find that sending messages with the factory like in the demo, when spanning multiple SMS, they come through in the wrong order.

Google Voice seems to prepend `(i/n) ` to the texts and add a delay in between.

Sure, this is something that could be in the app layer, but would be nice to have helpers in the API :)

**Comment by skimbrel** [comment]
Are you using the SmsFactory or MessageFactory implementation? The underlying REST API resources have different semantics and Twilio will automatically split large messages for you when using the /Messages endpoint (MessageFactory). Unfortunately the order of delivery to the recipient is up to the actual carrier.

If you need further help with sending concatenated messages, can you contact help@twilio.com? This repo isn't always monitored closely, and Support will always get back to you in 24 hours.

**Comment by patcon** [comment]
I was using MessageFactory fwiw. Thanks for the heads up. I'll close this out :)
