### ISSUE TITLE
org.apache.httpcomponents.httpclient classes deprecated in most recent version

### ISSUE THREAD

**Issue by tkondrashov** [twilio/twilio-java#206]
Some classes used in the library, including PoolingClientConnectionManager, are deprecated in the version of httpclient that ships with android studio. It is now replaced with PoolingHttpClientConnectionManager. People (such as myself) may be uncomfortable using a deprecated library, so updating the use of these classes to be current would make using the API easier.

**Comment by mittalharsh54** [comment]
what is the solution to this, i am stuck on this issue since a week. Also i am getting the  duplicate class error of org.apache as the same apache classes are already in other dependency in my project

**Comment by jingming** [comment]
We have released version `7.0.0` which uses the `PoolingHttpClientConnectionManager`.
