### ISSUE TITLE
General Twilio Bug: Dial Number status callbacks are broken

### ISSUE THREAD

**Issue by 4np** [twilio/twilio-java#207]
The _premium_ event callbacks (they are $0.0001 per callback) for a Dial's Number seem broken and either report wrong information or do not execute at all. 

Example: construct the number to execute event callbacks (```"initiated ringing answered completed"``` like [documented](https://www.twilio.com/docs/api/twiml/number#examples-3), see below example). When the dial is executed the callback url will receive the __initiated__ event, but never the __ringing__ event (event though the phone number configured is ringing). When the phone call is answered the callback url will never receive the __answered__ event and when the phone call finishes (the _called_ number hangs up) the callback url will receive the _undocumented_ __no-answer__ event and never the __completed__ event.

_note: when using a Client verb instead of a Number verb the behaviour seems to be as expected, although **ringing** comes before **initiated**..._

Code example:
```java
// see https://www.twilio.com/docs/api/twiml/dial
Dial dial = new Dial();
dial.setMethod("POST");
        
// see https://www.twilio.com/docs/api/twiml/number
Number number = new Number("+31....."); // some number
number.setUrl(actionURL); // some status callback url
number.setMethod("POST");

// configure what event callbacks to execute (not that this costs $0.0001 per event!)
// see https://www.twilio.com/docs/api/twiml/number#examples-3
number.set("statusCallbackEvent", "initiated ringing answered completed");
number.set("statusCallbackMethod", "POST");
number.set("statusCallback", statusCallbackURL);
dial.append(number);
```

The above example will generate proper TwiML:
```
<Response>
<Dial method="POST" timeout="30" action="http://...dialActionURL">
<Number url="http://...dialActionURL" method="POST" statusCallbackEvent="initiated ringing answered completed" statusCallbackMethod="POST" statusCallback="http://...dialStatusCallbackURL">+31205655552</Number></Dial>
</Response>
```

But it will only trigger _two_ event callbacks:

The _initiated_ event:
```
CallbackSource=call-progress-events
AccountSid=AC...e
CallStatus=initiated
CalledVia=+14...
Called=+3120...
To=+3120...
ParentCallSid=CA...e
SequenceNumber=0
Timestamp=Mon, 01 Jun 2015 10:37:47 +0000
Direction=outbound-dial
ApiVersion=2010-04-01
ForwardedFrom=+14...
Caller=+316...
CallSid=CA...5
From=+316...
```

The (incorrect and undocumented) _no-answer_ event (when the call was finished):

```
CallbackSource=call-progress-events
AccountSid=AC...e
CallStatus=no-answer
CalledVia=+14...
Called=+3120...
To=+3120...
ParentCallSid=CA...e
SequenceNumber=1
Timestamp=Mon, 01 Jun 2015 10:37:54 +0000
Direction=outbound-dial
ApiVersion=2010-04-01
ForwardedFrom=+14...
Caller=+316...
CallSid=CA...5
From=+316...
```

__Expected event callbacks__:
1. initiated
2. ringing
3. completed

**Comment by skimbrel** [comment]
Hey Jeroen,

I've escalated this to our voice engineers. In general this GH repo isn't the appropriate place for anything other than bugs found directly in the helper library; our Support team (help@twilio.com) is better equipped to handle issues with the platform itself. Can you open a ticket with them and reference this issue / tell them I sent you?

Sam

**Comment by 4np** [comment]
Hi Sam,

Thanks for getting back. I contacted support and refered to this GitHub issue... 

Cheers, Jeroen

**Comment by GauravTejpal** [comment]
Hello @4np ,

Is your issue resolved , i am also facing issue while hanging up the Call as Twilio is posting Ringing Status to me but when i try to Hangup that call it is showing CallStatus Queued.
