### ISSUE TITLE
Sms.getResourceLocation() uses deprecated /SMS/Message API endpoint

### ISSUE THREAD

**Issue by dampier** [twilio/twilio-java#208]
Looking at https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/resource/instance/Sms.java#L54-L57

seems SMS messages are created and sent using the ```/SMS/Messages.json``` endpoint; API documentation however strongly steers away from that and toward ```/Message.json``` endpoint.

Source: https://www.twilio.com/docs/api/rest/message

One serious downside of using the older endpoint seems to be that message status will at best end up as ```'sent'```; using the newer endpoint apparently makes it possible to have such messages' status end up as either ```'delivered'``` or ```'undelivered'``` -- which is **much** more useful from the client's perspective.

Source: https://www.twilio.com/help/faq/sms/why-are-my-messages-status-sent

**Comment by dampier** [comment]
Hmm .. okay, partly this is the fault of (old) client code, doing this 

```java
        TwilioRestClient client = getMessageSender();
        SmsFactory messageFactory = client.getAccount().getSmsFactory();
```

and calling ```messageFactory.create()``` ... 
it looks like what one should be doing instead is 

```java
        TwilioRestClient client = getMessageSender();
        MessageFactory messageFactory = client.getAccount().getMessageFactory();
```
So ... there is probably a large component of pilot error here.  :/

**Comment by skimbrel** [comment]
Yep, using the MessageFactory is the way you want to go here. Let us know if you run into issues with it. I suppose we could add a deprecated annotation to the old Sms stuff...

**Comment by dampier** [comment]
Awesome -- thank you.  
Switching to MessageFactory did the trick all right.
Deprecation for the SMS stuff (per #209 now) sounds like the right thing going forward.

Thanks again!
TD
