### ISSUE TITLE
Queue: member.getQueueSid() will be null, causing member.update() to fail

### ISSUE THREAD

**Issue by 4np** [twilio/twilio-java#213]
When getting a queue and a queue member by, respectively, ```queue sid``` and ```call sid```, the member's internal reference to the queue is null.

Example (also see the [Twilio Example](https://www.twilio.com/docs/api/rest/member#instance-post-example-2)):
```java
		    Account account = getRestClient().getAccount();
		    Queue queue     = account.getQueue(queueSID);
		    Member member   = queue.getMember(callSID);

		    System.out.println("member's queue sid: " + member.getQueueSid());
```

(where getRestClient() returns ```new TwilioRestClient(...)``` )

The member's ```queueSid``` will always be ```null```, causing any subsequent ```update``` calls to fail:

```
The requested resource /2010-04-01/Accounts/AC.../Queues/null/Members/CA....json was not found
```

Note that the URL is trying to pass ```null```...

_**Workaround**_
If you get the ```Member``` instance by _iterating_ over the ```Queue```'s members, the ```Member``` instance _is_ properly instantiated with the right ```Queue SID```:

```
		    MemberList members = queue.getMembers();
		    for (Member member : members) {
			    // check if the member's callSID matches the passing callSID
			    if (member.getCallSid().equals(callSID)) {
				    System.out.println("member's queue sid: " + member.getQueueSid());
			    }
		    }
```

**Comment by skimbrel** [comment]
What version of the library are you using? I can't seem to reproduce this.

**Comment by jingming** [comment]
Answered.
