### ISSUE TITLE
ListResource.hasNextPage is inaccurate and leads to NoSuchElementException

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#217]
Since `next_page_uri` is always populated now, `ListResource.hasNextPage()` always returns `true` as does `ListResource.ListIterator.hasNext()`.

This leads to problems if you attempt to iterate through a list resource, e.g.

```
		for (Call call : calls) {
                }
```

as it will throw a `NoSuchElementException` when attempting to `next()` past the last element.

```
java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:350)
	at com.twilio.sdk.resource.ListResource$ListIterator.next(ListResource.java:60)
	at com.twilio.sdk.resource.ListResource$ListIterator.next(ListResource.java:21)
	at com.twilio.calltest.CallTest.listCallsTest(CallTest.java:411)
...
```

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/resource/ListResource.java#L167

**Comment by Richiecakes** [comment]
Bump - also getting this :(

**Comment by senthgit** [comment]
@alexcchan & @Richiecakes a fix for this issue was rolled out 3 days ago. Please use twilio-java-sdk-5.7.1 or latest.
