### ISSUE TITLE
NullPointerException thrown by XmlResponseParser when trying to query UsageRecords

### ISSUE THREAD

**Issue by Richiecakes** [twilio/twilio-java#219]
Null Pointer Exception thrown when trying to execute this code
```java
UsageRecordList usageRecords = account.getUsageRecords(usageFilters);
        for (UsageRecord record : usageRecords) {
            // Do stuff
        }
}
```
![exceptionstacktrace](https://cloud.githubusercontent.com/assets/6248193/9115436/f8d36b4e-3c56-11e5-8046-1a94728e9a13.png)

<br>
Making a request using the API explorer shows that the nextpageuri field is blank.

![notspecified](https://cloud.githubusercontent.com/assets/6248193/9115706/62c2daa2-3c58-11e5-9362-5c57263950b7.png)

<br>

I think this code found in XmlResponseParser.java is interpreting the empty parameter as null but I'm not sure.

![nullpointer](https://cloud.githubusercontent.com/assets/6248193/9115626/10c70598-3c58-11e5-8285-0a39925cc16f.png)
![requiredproperty](https://cloud.githubusercontent.com/assets/6248193/9115628/1370b7da-3c58-11e5-9fb0-8d9b8233e342.png)

**Comment by Richiecakes** [comment]
On closer inspection, the **numpages** and **total** attributes are missing completely, so it's probably those which are causing
```java
attrs.getNamedItem(property)
```
to return null

**Comment by vincentjames501** [comment]
+1

**Comment by vincentjames501** [comment]
This is a major issue that just affected us in production. Twilio, please fix issues like these in your official clients. I'm not sure why these params are even gone as it wasn't supposed to be for another two days until that was released and the client still hasn't been updated to properly support these missing parameters.

**Comment by jingming** [comment]
The NPE as a result of the deprecated fields *numpages* and *total* no longer being returned has been in addressed in the latest release of the helper library.
