### ISSUE TITLE
Fatal signal 7 (SIGBUS) at 0x68651377 (code=2) for Twilio-android  registered in remote process  for Android

### ISSUE THREAD

**Issue by rambabupudari** [twilio/twilio-java#223]
Hi ,
when i initialize the twilio-android sdk  in remote process, app is getting crashed.

here is the crash log..
Fatal signal 7 (SIGBUS) at 0x68651377 (code=2), thread 7294 (Thread-10449)
pjsua_acc.c .....Unable to create/send REGISTER: Object is busy (PJSIP_EBUSY) [status=171001]
A/libc﹕ Fatal signal 7 (SIGBUS) at 0x68651377 (code=2), thread 7294 (Thread-10449)

please help me out form this is issue.

**Comment by jingming** [comment]
If you are still seeing this issue, please contact help@twilio.com
