### ISSUE TITLE
twilio Give Generic Error

### ISSUE THREAD

**Issue by androidappaspect** [twilio/twilio-java#227]
I am working with Twilio android SDK. and Some time it Gives Application not Found Error and Some time It Gives Generic Error While Some time Its Working what is the issue?

**Comment by carlosdp** [comment]
Hi @androidappaspect, can you give us an actual error output from the application to take a look at?

**Comment by androidappaspect** [comment]
Hello !!!  @carlosdp .


I'm Facing Two Type  of issue.

1.Implemented SomeTime Twilio is  Give me Twilio Client Error  While I'm Try  to make a call.but Its Work Fine Some Time.its Give me Error On Log.

09-30 10:59:35.250    E/onConnectionStateChange Message:﹕ Connection state changed from [DISCONNECTED] to [CONNECTING]
09-30 10:59:36.620    E/Status Message:﹕ onConnectionFailedConnecting(Exception error) - Application not found
09-30 10:59:36.940    E/onConnectionStateChange Message:﹕ Connection state changed from [CONNECTING] to [CONNECTED]


2.Twilio is Working Fine Before one week with same code that was connected at that time but now while if its not give me Twilio Client Error  then its Directly Go to onConnectionDisconnected().

"CODE"---->
         phone = BasicPhone.getInstance(getApplicationContext());
        phone.setListeners(this, this, this);
        phone.login(twilioCapabilityToken); 

"IN A BasicPhone.java"---->

**Comment by jingming** [comment]
If you are still seeing this issue, please contact help@twilio.com
