### ISSUE TITLE
Jackson Or JsonSimple. Not both

### ISSUE THREAD

**Issue by georgantasp** [twilio/twilio-java#232]
Follow up to dependency issue #130 .

Part of my gripe was that this library is dependency heavy. If you require a dependency for JSON, pick one. Only one.

**Comment by codylerum** [comment]
Proposal to drop json-simple #233

**Comment by husayt** [comment]
I also join to suggest to use only Jackson and also it is long overdue to switch to jackson 2, which is so much more reliable and better.

**Comment by jingming** [comment]
version `7.0.0` only uses Jackson.
