### ISSUE TITLE
Which version of the Java Twilio API supports SHA2-signed certificates

### ISSUE THREAD

**Issue by mrueegg** [twilio/twilio-java#235]
As Twilio is moving to SHA2-signed certificates at Dec 1st, which version of the Twilio Java API is compatible with this change?

Thanks,
Michael

**Comment by carlosdp** [comment]
It should work with all recent versions of the library. If you would like to test your version with your application, you can initialize a Twilio client and then set the port to our SHA2 test port `8443` like so:

```java
client.getHttpClient().getHostConfiguration().setHost('api.twilio.com', 8443);
```

**Comment by mrueegg** [comment]
Thanks, I've just verified that my application still works by using api.twilio.com with port 8443.
