### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.conn.PoolingClientConnectionManager" on path: DexPathList[[zip file "/data/app/com.example.myapplication-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by ThangPk** [twilio/twilio-java#242]
I got an error as title when running example of sending email on run time. I am using version: 5.0.8. Could you please help how to resolved it!

Thanks so much.

**Comment by panchenko** [comment]
It seems like the following dependency is missing:
```xml
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpcore</artifactId>
<version>4.2.5</version>
```

**Comment by ThangPk** [comment]
Thanks @panchenko  for your comment, how about this error:

java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;ILorg/apache/http/conn/scheme/SchemeSocketFactory;)V in class Lorg/apache/http/conn/scheme/Scheme; or its super classes (declaration of 'org.apache.http.conn.scheme.Scheme' appears in /system/framework/ext.jar)
            at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:50)
            at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:95)
            at com.twilio.sdk.TwilioClient.<init>(TwilioClient.java:147)
            at com.twilio.sdk.TwilioRestClient.<init>(TwilioRestClient.java:23)
            at com.twilio.sdk.TwilioRestClient.<init>(TwilioRestClient.java:19)

**Comment by panchenko** [comment]
It seems like you are running this on Android (I've just noticed "apk" in the message). Android has some outdated version of HttpClient built-in, so this library can't be run without changes.
What you can do:
- use twilio API directly
- use twilio from your server
- change sources of this library to use android port of httpclient and recompile it
