### ISSUE TITLE
Get channel using UniqueName

### ISSUE THREAD

**Issue by usmanchaudhri** [twilio/twilio-java#246]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
6.2.0-edge

**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```java
# paste code here
        TwilioIPMessagingClient client = new TwilioIPMessagingClient(ACCOUNT_SID, AUTH_TOKEN);
        Service service = client.getService(SERVICE_SID);
        Channel channel = service.getChannel(uniqueName);
        return Response.status(Response.Status.OK).entity(channel).build();
```

### Exception / Log
```
! Causing: com.fasterxml.jackson.databind.JsonMappingException: Property last_consumed_message_index does not exist (through reference chain: com.twilio.sdk.resource.instance.ipmessaging.Channel["members"]->com.twilio.sdk.resource.list.ipmessaging.MemberList["pageData"]->java.util.UnmodifiableRandomAccessList[0]->com.twilio.sdk.resource.instance.ipmessaging.Member["lastConsumedMessageIndex"])
! at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210) ~[jackson-databind-2.5.1.jar:2.5.1]
```

### Steps to Reproduce
1. Create a Channel with unique name.
2. Make a Get call with channel created with Unique Name above.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by jingming** [comment]
@usmanchaudhri This looks like an error in trying to parse the field `last_consumed_message_index` which is not a property. This has addressed in version `7.0.0` of the library and you can fetch by a unique name here: https://github.com/twilio/twilio-java/blob/twilio-7.0.0/src/main/java/com/twilio/rest/ipmessaging/v1/service/Channel.java#L78
