### ISSUE TITLE
Object names

### ISSUE THREAD

**Issue by llSourcell** [twilio/twilio-java#250]
### Feature Request
I feel like it would be more intuitive if we had a single object per resource in the notifications SDK. So instead of BindingFetcher, BindingReader, etc. -- we have one object 'Binding' with methods that equate to the requests (Binding.fetch, Binding.read). Just a thought!

**Comment by ihumanable** [comment]
That exact thing exists, https://github.com/twilio/twilio-java/blob/twilio-java-sdk-7.0.0-rc-2/src/main/java/com/twilio/sdk/resource/notifications/v1/service/Binding.java
