### ISSUE TITLE
next-gen: ACCOUNT_SID passed twice

### ISSUE THREAD

**Issue by panchenko** [twilio/twilio-java#263]
Looking at https://www.twilio.com/docs/libraries/java#installation-nextgen: ACCOUNT_SID is passed to both
* Twilio.init()
* new MessageCreator()

**Comment by jingming** [comment]
We will be adding another constructor to these classes that does not require an account sid. If you use that constructor, `execute` will use `getAccountSid()` of the passed in client.

**Comment by jingming** [comment]
This has just been pushed to the `next-gen` branch and will go out with the next release candidate.

**Comment by jingming** [comment]
This was released as part of `7.0.0-rc-12`.
