### ISSUE TITLE
next-gen: static fields in the Twilio class

### ISSUE THREAD

**Issue by panchenko** [twilio/twilio-java#264]
Looking at https://www.twilio.com/docs/libraries/java#installation-nextgen: it all starts with `Twilio.init(ACCOUNT_SID, AUTH_TOKEN)`. What if I would like to use it with 2 accounts?

**Comment by jingming** [comment]
`Twilio.java` acts more like a convenience class if you would only like to use a single account with the default client. If you would like to use more than one account, you can create multiple `TwilioRestClient`s and pass the desired client when calling `.execute`.
