### ISSUE TITLE
next-gen: would it makes sense to remove com.ning:async-http-client:jar:1.8.14 dependency?

### ISSUE THREAD

**Issue by panchenko** [twilio/twilio-java#265]
Seems to be used only in src/main/java/com/twilio/sdk/http/NingHttpClient.java which does strange thing by firing async request and then waiting.

The problem is netty 3.9.2 as a transitive dependency on this one, while we already have netty 4.

The less dependencies -  the better.

**Comment by jingming** [comment]
Removed this dependency in the `next-gen` branch, it will go out with then next release-candidate.

**Comment by jingming** [comment]
This was released as part of `7.0.0-rc-12`.
