### ISSUE TITLE
Next-gen: use new java 8 date/time types instead of joda-time

### ISSUE THREAD

**Issue by panchenko** [twilio/twilio-java#268]
Java 7 from Oracle is already EOL, java 8 was released >2 years ago. While doing a major library update it would make sense to use new java8 types, instead of an external dependencies.

Also, those types could be used for deserialization directly by adding the https://github.com/FasterXML/jackson-datatype-jsr310 dependency.
So, instead of manually calling methods like DateConverter.iso8601DateTimeFromString property could initially declared with the corresponding type.

**Comment by jmctwilio** [comment]
Because we have so many customers who rely on Java 7 (despite it's EOL), we're focusing right now on supporting Java 7.
