### ISSUE TITLE
Twilio Java SDK 7.x not Object Oriented, using global state?

### ISSUE THREAD

**Issue by ceefour** [twilio/twilio-java#270]
**Version:** 7.0.rc-10
**API Subdomain (api/taskrouter/ip_messaging):** api

### Code Snippet
```java
Twilio.init(accountSid, authToken);
```

### Feature Request

This seems to be counter to Java best practices including the Spring programming model.

It seems to be using a global state. Which creates a number of issues. One I can think of is a long-running multitenant webapp. It may host several Twilio accounts, one (or more?) for each tenant. A tenant can change their account SID and/or auth token at any time, or remove their Twilio configuration.

On this case only, I prefer the old way, where a `TwilioRestClient` is using a defined accountSid/authToken and has a clearly manageable lifecycle.

**Comment by ihumanable** [comment]
Although we offer the `Twilio.init()` method as a convenience, the library still (and will always) support explicit client lifecycle management.

All actions are initiated through either the `execute()` or `async()` method, this method accepts a `TwilioRestClient` argument so that you can have finer grained control over the Client.

For example:
```java
import com.twilio.rest.http.TwilioRestClient;
import com.twilio.rest.resource.api.v2010.account.Call;

TwilioRestClient client = new TwilioRestClient(accountSid, authToken);

Call call = Call.fetch('CAaaaaaaaaaaaaaaaaaaaaaaaaaaa').execute(client);
```

**Comment by panchenko** [comment]
> why repeat the accountSid here?

I've already filed this as #263

**Comment by jingming** [comment]
This was released as part of `7.0.0-rc-12`.

**Comment by ceefour** [comment]
Thanks @jingming , where /when can I get rc12? The latest I found in Maven Central is still rc10.

**Comment by jingming** [comment]
It is found here: http://search.maven.org/#artifactdetails%7Ccom.twilio.sdk%7Ctwilio%7C7.0.0-rc-12%7Cjar

We released it under a new artifact name so that you can install both versions side by side and do gradual migration.

**Comment by ceefour** [comment]
Thank you! :+1:
