### ISSUE TITLE
Support for MessagingServiceSid / Copilot

### ISSUE THREAD

**Issue by ceefour** [twilio/twilio-java#271]
**Version:** 7.0.rc-10
**API Subdomain (api/taskrouter/ip_messaging):** api

### Code Snippet
```java
final SmsMessage smsMessage = new SmsMessageCreator(accountSid, new PhoneNumber(mobileNumber), 
                new PhoneNumber(fromNumber), message).execute(twilio);
```

Where is `SendMessageWithService()` replacement ?

### Regression

https://www.twilio.com/docs/api/rest/sending-messages-copilot#services needs to be supported.

**Comment by jingming** [comment]
This has been created in `Message` (https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/rest/creator/api/v2010/account/MessageCreator.java#L77) and will go out with the next release candidate.

Also note that `/SMS/Messages` resource has been deprecated (https://www.twilio.com/docs/api/rest/sms) and will removed.

**Comment by ceefour** [comment]
Thanks @jingming ^_^
