### ISSUE TITLE
Class Name Misleading (next-gen)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#272]
**Version:** 7.0.0-rc-14
**API Subdomain (api/taskrouter/ip_messaging):** API

### Code Snippet
```java
ResourceSet<Call> calls =
    new CallReader().byFrom(new PhoneNumber("client:tommy")).execute();
```

Snippet above will actually work and filter correctly (I tried). But the `PhoneNumber` class name is misleading and there is no overloaded method `byFrom` that takes a client as argument. This is something that probably can change across the whole library. Create a `Client` type? 

I didn't add the yoyodyne label because I don't have access to this repository.

**Comment by jingming** [comment]
a new type `Endpoint` was added in `7.0.0-rc-17`. Both `PhoneNumber` and `Client` implement it.
