### ISSUE TITLE
No Message Creator with Body and mediaUrl (next-gen)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#277]
**Version:** 7.0.0-RC19
**API Subdomain (api/taskrouter/ip_messaging):** api

There is no constructor in [MessageCreator](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/rest/api/v2010/account/MessageCreator.java) that will allow the creation of a message with (toNumber, fromNumber, body, mediaUrl). There is no combination of (body, mediaUrl) and no method to set one of those.

API does support both parameters in the same request.

**Comment by jingming** [comment]
Fixed in `7.0.0-rc-20`

**Comment by mcelicalderon** [comment]
👍
