### ISSUE TITLE
Wrong parameter type in CallCreator (next-gen)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#279]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** API

The new Endpoint interface is great for `Client` and `PhoneNumber` types. But, parameters are inverted in [Call Creator](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java#L54) the `to` parameter type should be `Endpoint` and the `from` parameter should be `PhoneNumber`

**Comment by mcelicalderon** [comment]
@jingming There is something else to add in this issue. There is another `EndPoint` other that the already existing `Client` and `PhoneNumber`. There is also `sip`. [Here](https://www.twilio.com/docs/api/rest/making-calls#post-parameters-required) are the required params from the docs. `To` number can be in the format `sip:kate@example.com?hatchkey=4815162342`.

Also, the `from` parameter can also be a sip client. Please refer to [this code snippet](https://github.com/TwilioDevEd/api-snippets/tree/master/rest/sip/example-3) for more details, I don't have a better source to support this functionality.

**Comment by jingming** [comment]
Will add a `Sip` type that implements `Endpoint`.

**Comment by jingming** [comment]
Released in `7.0.0-rc-22`
