### ISSUE TITLE
Non optional muted parameter (Participant/Update)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#280]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** api

The [update action on the conference->participant resource](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/rest/api/v2010/account/conference/ParticipantUpdater.java#L33) has a non optional `muted` parameter.

Docs don't mention muted as a required parameter

**Comment by jingming** [comment]
This appears to be fixed.
