### ISSUE TITLE
Non optional `Credential` update params

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#281]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** API

[The docs](https://www.twilio.com/docs/api/rest/credential#instance-post-credential) are not very clear about this one, maybe you can ask internally, but right now when updating a credential, both `username` and `password` are mandatory for the update action. I know that at least `username` is not mandatory based on previous code snippets.

**Comment by jingming** [comment]
It looks like you can only update the `Password` and it is optional. We will make that change.

**Comment by jingming** [comment]
Released in `7.0.0-rc-22`
