### ISSUE TITLE
Non optional available parameter (Activity/Create)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#282]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** taskrouter

There is only one constructor for [ActivityCreator](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/rest/taskrouter/v1/workspace/ActivityCreator.java#L32) which takes (`workspace_sid`, `friendly_name`, `available (bool)`).

`Available`  is an optional parameter that defaults to `false` (from the docs)

**Comment by jingming** [comment]
Check with the team. There are some API changes required and we will make those and then update these definitions.

**Comment by jingming** [comment]
This has been released in `7.0.0-rc-28`
