### ISSUE TITLE
TaskRouter Statistics Value Access

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#283]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** taskrouter
### Feature Request

This is not an issue, but if there is a way with Yoyodyne to get more expressive types on this particular resource (Statistics, for workers, taskqueues, workflows) it would be great. As you can see in the snippet below the `getCumulative()` and `getRealTime()` return a `Map<String, Object>` and for some values this `Object` is again a Map. It is possible to work with that, but it'd be nice to be able to get this values without casting objects or having to know the names of the parameters delivered in the payload. This is already implemented in the legacy version of this library.

Again, this wouldn't be hight priority (other libraries like PHP next-gen and Python legacy do the same), but it would be a nice feature, if possible.
### Code Snippet

``` java
// Install the Java helper library from twilio.com/docs/java/install
import java.util.Map;

import com.twilio.Twilio;
import com.twilio.rest.taskrouter.v1.workspace.workflow.WorkflowStatistics;

public class Example {
  private static final String ACCOUNT_SID = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
  private static final String AUTH_TOKEN = "your_auth_token";
  private static final String WORKSPACE_SID = "WSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
  private static final String WORKFLOW_SID = "WWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

  public static void main(String[] args) {
    Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

    WorkflowStatistics statistics = WorkflowStatistics.fetch(WORKSPACE_SID, WORKFLOW_SID).execute();

    Map<String, Object> cumulative = statistics.getCumulative();
    Map<String, Object> realtime = statistics.getRealtime();
    Map<String, Object> tasksByStatus = (Map<String, Object>) realtime.get("tasks_by_status");

    System.out.println("Avg Task Acceptance Time: " + cumulative.get("avg_task_acceptance_time"));
    System.out.println("Tasks Entered: " + cumulative.get("tasks_entered"));
    System.out.println("Pending Tasks: " + tasksByStatus.get("pending"));
    System.out.println("Assigned Tasks: " + tasksByStatus.get("assigned"));
  }
}
```

**Comment by jmctwilio** [comment]
Thank you for your suggestion.  Supporting JSON and nested objects is on our roadmap.
