### ISSUE TITLE
TwiML -> Enqueue should allow Task as a Noun

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#284]
**Version:** 7.0.0-RC20
**API Subdomain (api/taskrouter/ip_messaging):** TwiML

TwiML generation for next-gen allows [`Enqueue` verb](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/twiml/Enqueue.java) only to receive a String with the Queue name. It should also allow to set a `Task` as an Enqueue's noun. [From the docs](https://www.twilio.com/docs/api/twiml/enqueue#nouns)

**Comment by jingming** [comment]
Will add the `Task` noun to `Enqueue`.

**Comment by jingming** [comment]
Released in `7.0.0-rc-22`
