### ISSUE TITLE
Missing Attributes Parameter next-gen

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#285]
**Version:** 7.0.0-RC21
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

The [Service -> Channel -> Message](https://www.twilio.com/docs/api/ip-messaging/rest/messages#parameters) resource can't be created with the Attributes optional parameter. It looks like this property is not included in the definitions.

**Comment by jingming** [comment]
Released in `7.0.0-rc-22`
