### ISSUE TITLE
Role Update friendlyName

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#286]
**Version:** 7.0.0-RC21
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

[The docs](https://www.twilio.com/docs/api/ip-messaging/rest/roles#action-update) do say you can update a Role's friendlyName, but I have tried to do it with and without the library and apparently it is not possible, you can only update permissions. 

It would be nice to confirm internally and update the definitions and API docs if necessary.

**Comment by jingming** [comment]
Currently, this is not a supported feature.

**Comment by mcelicalderon** [comment]
@jingming  So it will be removed from the definitions? Currently this next-gen library "allows you to update" a friendlyName, leaving that is misleading for the user as the actual API doesn't allow that operation. I would also have to update the docs.

**Comment by jingming** [comment]
yes, we will remove it from the definitions.

**Comment by mcelicalderon** [comment]
I'm reopening this until the fix is released so I don't forget about it. The docs are already updated.

**Comment by mcelicalderon** [comment]
Also, once the definitions are updated, PHP library should be regenerated too.

**Comment by jingming** [comment]
Closing, as this update has been released.
