### ISSUE TITLE
Non optional ROLE_SID create param (ipm->user)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#287]
**Version:** 7.0.0-RC21
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

[The docs](https://www.twilio.com/docs/api/ip-messaging/rest/users#parameters) are not very clear on what parameters are mandatory for User creation, but I have tested it myself and only `Identity` is mandatory. Current library also requires `ROLE` for user creation. When no `ROLE` is specified, the default role for that service is set.

**Comment by jingming** [comment]
It looks like only `Identity` is required. I will make that change.

**Comment by jingming** [comment]
Released in `7.0.0-rc-22`
