### ISSUE TITLE
Unable to nest TwiML verbs within other verbs

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-java#292]
**Version:** 7.0.0-rc-25
**API Subdomain (api/taskrouter/ip_messaging):** TwiML

Next-gen TwiML generation won't allow to nest more than one verb of the same type within other verbs. The snippet below will overwrite the nested say verb every time `say()` is called. And more important than that, order won't be preserved even if you nest only one verb of each kind as they are just properties of the Gather verb disregarding the order in which they were added.

### Code Snippet
```java
Gather gather = new Gather.Builder()
        .action("/conference/connect")
        .method(Method.POST)
        .say(sayMessage)
        .say(sayOption1)
        .say(sayOption2)
        .say(sayOption3)
        .build();
```

I know [Gather verb](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/twiml/Gather.java) presents this issue, also [Message verb](https://github.com/twilio/twilio-java/blob/next-gen/src/main/java/com/twilio/twiml/Message.java) should support multiple `Media elements`.

There might be other cases where multiple nested (ordered) verbs need to be supported. Not sure which ones.

**Comment by jingming** [comment]
This is fixed in `7.0.0-rc-26`
