### ISSUE TITLE
MessagingServiceSid

### ISSUE THREAD

**Issue by tmduncan** [twilio/twilio-java#298]
Is it just me or does the 7+ java sdk not include a way to use the MessagingServiceSid?  Maybe I'm missing something or its fallen out of favor.

**Comment by jingming** [comment]
@tmduncan You can send a new message using a`messagingServiceSid` here: https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/rest/api/v2010/account/Message.java#L184

**Comment by tmduncan** [comment]
Is there a plan to push the later versions for Maven builds?
