### ISSUE TITLE
org.apache.httpcomponents.httpclient  4.5.2 conflicting with internal version by Android

### ISSUE THREAD

**Issue by mmarshak** [twilio/twilio-java#300]
Hi

I added to my Gradle file in the latest Android Studio the following -
compile 'com.twilio.sdk:twilio:7.0.1'

And when I build I get the following warning-

Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.2 is ignored for debug as it may be conflicting with the internal version provided by Android.
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.2 is ignored for release as it may be conflicting with the internal version provided by Android.
Information:2 warnings

Any suggestions?

**Comment by aahtesham** [comment]
Please Udate The httpClient for add Dependiences

**Comment by tmconnors** [comment]
@mmarshak This library is not supported for usage on the Android platform. The Android platform uses an older fork of the Apache Http Client, prior to API 23, than this helper library utilizes. Additionally, [Apache Http Client was removed in Android 6.0](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client). 

Furthermore, embedding Twilio account and authorization information in an APK is insecure. This information should be maintained on a secure server - which can make HTTP request to the [Twilio Rest AP](https://www.twilio.com/docs/api/rest) directly on behalf of your Android application.

For client HTTP requests from the android application I recommend using one of the following:

1. [HttpURLConection](https://developer.android.com/reference/java/net/HttpURLConnection.html)
2.[Ion](https://github.com/koush/ion)
3. [OkHttp](http://square.github.io/okhttp/)

**Comment by mmarshak** [comment]
@tmconnors you are right. Do you have by chance an example project that use OKHttp to talk with Node.js server based on express framework? I am looking for client code and server code (including the routing, security, etc...). This can be very helpful.

**Comment by tmconnors** [comment]
@mmarshak I'm not familiar enough with your stack or technologies to offer reliable advice. However, if you need further Twilio support contact help@twilio.com.

**Comment by HazemEngMuh** [comment]
how to integrate twilio with ok Http???

**Comment by shahzad1** [comment]
I'm facing same error. Can anybody help me?
