### ISSUE TITLE
How to Generate Capability Token For Client in Java Like Below code in Twilio 7.x

### ISSUE THREAD

**Issue by aahtesham** [twilio/twilio-java#304]
TwilioCapability capability = new TwilioCapability(account, auth_token);
				capability.allowClientOutgoing(applicationSid);
				capability.allowClientIncoming("Safr");
				try {
					System.out.println(capability.generateToken());
				} catch (DomainException e) {
					e.printStackTrace();
		}

This Code is not Supported in Twilio 7.x Please Tell me About this

**Comment by jingming** [comment]
hey @aahtesham!

The new version of the helper library migrated this to a builder pattern. To do the above you can use: 
```java
List<Scope> scopes = Lists.newArrayList(
    new OutgoingClientScope.Builder(APPLICATION_SID).build(),
    new IncomingClientScope("Safr")
);

Jwt jwt = new ClientCapability.Builder(ACCOUNT_SID, AUTH_TOKEN)
    .scopes(scopes)
    .build();

System.out.println(jwt.toJwt());
```
