### ISSUE TITLE
How to mock twilio in test env?

### ISSUE THREAD

**Issue by adamdziedzic** [twilio/twilio-java#310]
### Feature Request
In 6.x version there was base url passed to http client, so it was easy to pass there our own mocking seervice. How should we do this in 7.x version of sdk?

**Comment by jingming** [comment]
A good way to mock out any interaction with Twilio would be to create your own class (`MockClient`) that extends `HttpClient`. Then you would create a new `TwilioRestClient` that uses your `MockClient`. Now if you use the new `TwilioRestClient` you can have the `MockClient` return whatever response that you would like!

**Comment by jingming** [comment]
Closing as the question was answered.
