### ISSUE TITLE
Unable to set the ringTone in Twilio Java SDK 7

### ISSUE THREAD

**Issue by vsinha27** [twilio/twilio-java#311]
In the earlier version of Twilio sdk, I was able to set ringtone on the dial object as below
dial.set("ringTone", "nl"); 

In the Twilio Java SDK 7, there is no way to set the ringtone. When the call is redirected, we hear the default (USA) ringtone rather than the local (Netherlands) ringtone.

**Comment by jingming** [comment]
The `Dial` object now supports adding various attributes and we are also working on adding a dedicated `ringTone` parameter! 

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/twiml/Dial.java#L298
