### ISSUE TITLE
Missing "scope" attribute in Access Token JWT payload

### ISSUE THREAD

**Issue by katafractari** [twilio/twilio-java#312]
**Version: 7.3.0**

This one is probably related to https://github.com/twilio/twilio-node/issues/193
JS SDK expects jwt.scope attribute but Java AccessToken.Builder generates a JWT without it.

From https://www.twilio.com/docs/api/client/capability-token-spec:

> The most important part of the JWT payload is the scope field. This field is similar to the scope parameter used in OAuth2 in that it is a space delimited list of what specifically this token provides access to, or "scope of access"

### Java SDK access token generation method
```java
public Token createTwilioAccessToken(AppUser user) {
    String deviceId = "someid"
    String identity = user.getEmail();

    // Endpoint ID format: appName:identity:deviceId
    String endpointId = String.format("%s:%s:%s", Config.API_NAME, identity, deviceId);

    IpMessagingGrant grant = new IpMessagingGrant();
    grant.setEndpointId(endpointId);
    grant.setServiceSid("some_sid");

    AccessToken twilioToken = new AccessToken.Builder(Config.TWILIO_SUBACCOUNT_SID, Config.TWILIO_API_KEY,
            Config.TWILIO_API_SECRET).identity(identity).grant(grant).build();
    Token token = new Token(twilioToken.toJwt());

    LOGGER.info("Created channel token({}) for user({})", token, user);

    return token;
}

```

### JS SDK Device object initialization
```javascript
Twilio.Device.setup(<jwt in base64 format generated by above java method>, { debug: true });
```

### Exception / Log in JS SDK
```
twilio.js:3972 Uncaught TypeError: Cannot read property 'length' of undefined(…)objectize @ twilio.js:3972remainder @ twilio.js:3878Device @ twilio.js:792setup @ twilio.js:1255(anonymous function) @ twilio-service.js:44(anonymous function) @ cb=gapi.loaded_0:637(anonymous function) @ cb=gapi.loaded_0:605(anonymous function) @ cb=gapi.loaded_0:162_.T.E.__cb @ cb=gapi.loaded_0:97g @ cb=gapi.loaded_0:91c @ cb=gapi.loaded_0:82postMessage (async)(anonymous function) @ cb=gapi.loaded_0:49setTimeout (async)call @ cb=gapi.loaded_0:49call @ cb=gapi.loaded_0:66c.c.c.callback @ cb=gapi.loaded_0:57(anonymous function) @ cb=gapi.loaded_0:109A.onreadystatechange @ cb=gapi.loaded_0:108XMLHttpRequest.send (async)zu @ cb=gapi.loaded_0:109n @ cb=gapi.loaded_0:109Cu @ cb=gapi.loaded_0:109(anonymous function) @ cb=gapi.loaded_0:110g @ cb=gapi.loaded_0:58c @ cb=gapi.loaded_0:49postMessage (async)(anonymous function) @ cb=gapi.loaded_0:82d @ raven.js:367
```

### Steps to Reproduce
1. Generate access token on backend with latest SDK for Java following official Twilio documentation
2. Pass this token to a browser
3. Try to initialize Twilio.Device object with generated token

**Comment by jingming** [comment]
Hi @katafractari! 

The token that the provided code is generating is an `IPMessagingGrant`. If you are looking for the scope string when using a Client token, please use: https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/jwt/client/ClientCapability.java

**Comment by katafractari** [comment]
Thanks for pointing me in the right direction @jingming.
