### ISSUE TITLE
Message object returns numMedia and numSegments as String

### ISSUE THREAD

**Issue by eslavich** [twilio/twilio-java#314]
It's a little inconvenient that com.twilio.rest.api.v2010.account.Message returns String from getNumMedia() and getNumSegments().  Previous versions of the library used int for these fields, is it possible for the new library to continue to do so?  Thanks!

**Comment by tmconnors** [comment]
Hi @eslavich. I understand your frustration; however, unfortunately it will not be possible for the current generation of helper libraries. The goal of the current generation of helper libraries is to be consistent with the public REST API - which exposes these values as Strings. Sorry, we hope to resolve these inconsistencies and inconveniences in future generations.
