### ISSUE TITLE
Ending a Conference

### ISSUE THREAD

**Issue by katafractari** [twilio/twilio-java#316]
### Feature Request
Hi,

I need to end a conference via API but am unable to find a Conference.deleter or ConferenceDeleter class. Am I missing something or does this functionality still need to be implemented?

Cheers,
Rok

**Comment by jingming** [comment]
Are you referring to completing a conference? If so you can use `Conference.updater()` to update the conference with a `completed` status.

**Comment by katafractari** [comment]
@jingming I see! I'll look into it, thanks!
