### ISSUE TITLE
Record TwiML response is missing recordingStatusCallback

### ISSUE THREAD

**Issue by katafractari** [twilio/twilio-java#318]
I've noticed that com.twilio.twiml.Record.Builder doesn't have setRecordingStatusCallback method. I was wondering if you plan to implement it in the near future?

Thanks,
Rok

**Comment by TIMe747** [comment]
did you get an answer?

**Comment by katafractari** [comment]
@TIMe747 Yes. Record.Builder().recordingStatusCallback was implemented. Thanks for asking!

**Comment by TIMe747** [comment]
hey what imports i have to do? because i'm getting error says : 
The method recordingStatusCallback(String) is undefined for the type Record.Builder

**Comment by TIMe747** [comment]
i'm using twilio 7.4.0 jar

**Comment by katafractari** [comment]
Yeah it was merged in 7.5.0.

**Comment by Chprakash** [comment]
what should I pass in recordingStatusCallback(String)?
