### ISSUE TITLE
Call Progress Events - no `answered` - get `in-progress` instead

### ISSUE THREAD

**Issue by leonroy** [twilio/twilio-java#321]
Using the below code I'm making a call.

**Version:** Twilio Java API 7.3.0
**API Subdomain:** /api/calls

### Code Snippet
```java
        PhoneNumber phoneNumberTo = new PhoneNumber(to);
        PhoneNumber phoneNumberFrom = new PhoneNumber(from);
        com.twilio.rest.api.v2010.account.Call call = new CallCreator(phoneNumberTo, phoneNumberFrom, URI.create(twimlUrl))
                .setStatusCallback(URI.create(twStatusCallbackUrl))
                .setStatusCallbackEvent(Arrays.asList(
                        com.twilio.rest.api.v2010.account.Call.Event.ANSWERED.toString(),
                        com.twilio.rest.api.v2010.account.Call.Event.COMPLETED.toString(),
                        com.twilio.rest.api.v2010.account.Call.Event.INITIATED.toString(),
                        com.twilio.rest.api.v2010.account.Call.Event.RINGING.toString()))
                .create(this.client);
```

In the received events, the CallStatus parameters received are in the form:
### Exception / Log
```
1. initiated
2. ringing
3. in-progress
4. completed
```

### Steps to Reproduce
1. Make call via twilio calls api using Java lib - be sure to set status callback events
2. Received events contain` initiated, ringing, in-progress, completed`
3. Where's `answered` or is `in-progress` expected instead?

Just seems at odds with the event names being registered.

**Comment by imthepitts** [comment]
Hi @leonroy, Sorry for the confusion. The call status `in-progress` is indeed correct for the `answered` event. You can see the mapping between call statuses and events here:

https://support.twilio.com/hc/en-us/articles/223132547-What-do-the-call-statuses-mean-

Hope that helps.

**Comment by leonroy** [comment]
Thanks for confirming, although that link does suggest that the Call Status Event is named 'Answered' rather than 'in-progress'.

**Comment by jingming** [comment]
Closing as the question has been answered. Feel free to open if there are additional concerns.
