### ISSUE TITLE
Unable to configure sound payload parameter for iOS Push Notification using Java

### ISSUE THREAD

**Issue by ranjitsoni** [twilio/twilio-java#327]
Hi,

Problem Statement - I want to configure Sound Payload Parameter for iOS Push Notification over Twilio using java code but not able to find it. 
Additional Info - I checked link [**https://www.twilio.com/docs/api/chat/guides/push-notification-configuration**] where PHP example is given as below for configuring sound parameter but there is no example of Java.

$service = $client->services->get("YOUR_IP_MESSAGING_SERVICE_SID");
$response = $service->update(array(
    "Notifications.NewMessage.Enabled" => "true",
    "Notifications.NewMessage.Template" => "A New message in ${CHANNEL} from ${USER}: ${MESSAGE}",
    "Notifications.NewMessage.Sound" => "default",
));

Testing Environment :-- 
Twilio Version - 7
Java Version - 8
iOS Version- 10

Could anyone share code for configuring Sound Payload Parameter using Java.

Thanks in Advance

**Comment by jingming** [comment]
Please redirect this question to help@twilio.com.
