### ISSUE TITLE
Semantic Oddities - Nouns called Verbs

### ISSUE THREAD

**Issue by caseysoftware** [twilio/twilio-java#33]
The Numbers class:
https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/verbs/Number.java
which we normally refer to as a noun:
http://www.twilio.com/docs/api/twiml/number

is described as a verb and extends the Verb class. While this seems to work functionally, semantically it is inconsistent with our docs.

Conference is the same and there doesn't appear to be a verb (or noun) for Client within the Dial verb.

**Comment by jingming** [comment]
@caseysoftware This has been addressed in version `7.0.0` of the SDK. We have moved away from calling everything verbs and potential RuntimeExceptions when creating TwiML to using builder pattern. We hope this provides a much smoother process when using the TwiML generator.

**Comment by MikeGratsas** [comment]
In SDK version 6 constructor public Dial(String number) was implemented, but in version 7 constructor public Dial.Builder(String number) is missing. Therefore, it is impossible to create <Dial> TwiML verb with a phone number as inline XML directly
