### ISSUE TITLE
deserialization error

### ISSUE THREAD

**Issue by dimagoltsman** [twilio/twilio-java#338]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** 7.6.0
**API Subdomain (api/taskrouter/ip_messaging):** api

### Code Snippet
```java
new CountryFetcher("US").fetch(twilioRestClient)
```

### Exception / Log
```
com.twilio.exception.ApiException: Can not construct instance of com.twilio.type.InboundCallPrice$Type, problem: No enum constant com.twilio.type.InboundCallPrice.Type.TOLL FREE
 at [Source: org.apache.http.conn.EofSensorInputStream@7243145f; line: 1, column: 809] (through reference chain: java.util.ArrayList[1])

```

### Steps to Reproduce
1. run this new CountryFetcher("US").fetch(twilioRestClient)
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by efossier** [comment]
@dimagoltsman Thanks for reporting this, we've looked into it and does indeed look like there is a bug in our deserialization logic. We'll fix in the release.

**Comment by dimagoltsman** [comment]
@efossier  Thanx! that was fast

**Comment by jingming** [comment]
This has been deployed!
