### ISSUE TITLE
Channel attributes not populated when using ChannelReader

### ISSUE THREAD

**Issue by Antonio-Marrero-Medopad** [twilio/twilio-java#343]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**  7.7.0
**API Subdomain (api/taskrouter/ip_messaging):** com.twilio.rest.ipmessaging.v1.service.Channel

### Code Snippet
```java
ChannelReader chnlReader = new ChannelReader( twilioConfiguration.getIpmServiceSID());
ResourceSet<Channel> channels = chnlReader.read();
for(Channel chnl: channels){
              System.out.println("Channel ---- " + chnl.getAttributes());
}
```

### Steps to Reproduce
1. Create a new channel with attributes
2. Use ChannelReader to get the channel information
3. Check that the value of getAttributes() is always null

NOTE:  when using ChannelFetcher it works fine

**Comment by jingming** [comment]
@Antonio-Marrero-Medopad Thanks for flagging this issue!

We were able to replicate it using the API and have notified the appropriate team. We will keep you updated as we know more. If you wish, you may also file a ticket at help@twilio.com.

**Comment by efossier** [comment]
@Antonio-Marrero-Medopad Sorry for the late response, I've talked to the chat/ip-messaging team and this is actually expected behavior from their end. They expect to have a fix in the next month or so.
