### ISSUE TITLE
Dialer Callback Status issues-Twilio

### ISSUE THREAD

**Issue by GauravTejpal** [twilio/twilio-java#351]
Hello ,

I am facing the issue on hanging up the call, here is how i make a call.

  
[twilio.txt](https://github.com/twilio/twilio-java/files/920041/twilio.txt)

When request reaches Twilio, it makes Post request and there i am getting CallBack Status Ringing.

At the same time when i am trying to hangup the call , i checked detail of Call via RestApi and i am getting Status Queued .

I think this is only reason i am not able to hangup the Call.

Can anyone help me fix this bug here.

Thanks

**Comment by GauravTejpal** [comment]
<Response>
  <Dial action=\"" + Url + "\" timeout='120' callerId='+18559695363' method='GET'>
  <Number statusCallbackMethod='POST' statusCallback=\"" + StatusCallback + "\" statusCallbackEvent='initiated ringing answered completed'>Number</Number>"
 </Dial>"
</Response>

**Comment by efossier** [comment]
@GauravTejpal This doesnt sound like a python helper library issue. Please open a ticket at support@twilio com as they are better equipped to diagnose call bugs/issues.

**Comment by GauravTejpal** [comment]
@efossier  I have created this functionality in MVC C#.
