### ISSUE TITLE
English (Canada) and English (UK) constants are incorrect

### ISSUE THREAD

**Issue by dleshem** [twilio/twilio-java#367]
According to the [TWIML VOICE: Say](https://www.twilio.com/docs/api/twiml/say) documentation:
- English (UK) = ```"en_GB"```
- English (Canada) = ```"en_CA"```

However, [Language.java](https://github.com/twilio/twilio-java/blob/93cfbf8b9191b8e5aed61eea3c9d942a86f2513b/src/main/java/com/twilio/twiml/Language.java) currently defines:
- English (UK) = ```"en_gb"``` (all lowercase, inconsistent with the rest)
- English (Canada) = ```"en_GB"``` (typo?)

**Comment by jmctwilio** [comment]
<Say> supports "en-GB" as though it were "en-gb" but <Gather> prefers the former.
I've added 'GB' for use with <Say> for those who want to match case.
I've corrected the typo for "English (Canada)" to be "en-CA" as expected.
I've added a number of language constants now supported by <Gather>

#373
