### ISSUE TITLE
Code snippet on the README is outdated

### ISSUE THREAD

**Issue by apflieger** [twilio/twilio-java#395]
**Version: 7.16.0**

### Code Snippet
```java
Message message = Message.creator(
    new PhoneNumber("+15558881234"),  // To number
    new PhoneNumber("+15559994321"),  // From number
    "Hello world!"                    // SMS body
).create();
```

### Exception/Log
This doesn't compile

### Steps to Reproduce
This is the snippet on the README. I guess the API changed but I can't find the equivalent in the last version. I just need to send SMS :)

**Comment by jingming** [comment]
@apflieger What's the error you're seeing? Can you provide the code snippet that is failing?

**Comment by apflieger** [comment]
```java
Message message = Message.creator(
    new PhoneNumber("+15558881234"),  // To number
    new PhoneNumber("+15559994321"),  // From number
    "Hello world!"                    // SMS body
).create();
```
The method com.twilio.twiml.Message.creator doesn't exist

**Comment by jingming** [comment]
I think this is because you are using an incorrect import - try:
```java
import com.twilio.rest.api.v2010.account.Message;
```

**Comment by apflieger** [comment]
That's it, thanks!
