### ISSUE TITLE
Enable CallCreator to receive TwiML

### ISSUE THREAD

**Issue by acrespo** [twilio/twilio-java#396]
### Feature Request
It would be nice, when creating a Call via CallCreator, to be able to set the TwiML directly in the 
"constructor" method instead of passing an URI to a remote resource.

**Comment by thinkingserious** [comment]
Hello @acrespo,

Thanks for taking the time to submit this feature request! This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by frannnnk** [comment]
Is this one resolved ? I am also facing this issue.

**Comment by childish-sambino** [comment]
This was added in the [7.47.0](https://github.com/twilio/twilio-java/releases/tag/7.47.0) release. E.g.,
```
public static void main(String[] args) {
    Twilio.init(ACCOUNT_SID, AUTH_TOKEN);
    Call call = Call.creator(
        new com.twilio.type.PhoneNumber("+14155551212"),
        new com.twilio.type.PhoneNumber("+15017122661"),
        new com.twilio.type.Twiml("<Response><Say>Ahoy, World!</Say></Response>"))
    .create();
```

**Comment by frannnnk** [comment]
Oh.. I was talking to Twilio support a while ago for hours about this case.. Maybe you should update the example document [here](https://www.twilio.com/docs/voice/tutorials/how-to-make-outbound-phone-calls-java) .

**Comment by childish-sambino** [comment]
@frannnnk Yup, it needs updating. A ticket's being created to get it fixed, but it's an auto-generated sample so may not be trivial to update.

**Comment by craigsdennis** [comment]
Docs are all fixed now! Thank you for reporting this!
