### ISSUE TITLE
Phone Lookup failing when phone number have space in it

### ISSUE THREAD

**Issue by jubinpyli** [twilio/twilio-java#399]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:7.17.0**

### Code Snippet
`
        Twilio.init("SSID", "TOKEN");

        com.twilio.rest.lookups.v1.PhoneNumber number = com.twilio.rest.lookups.v1.PhoneNumber
            .fetcher(new com.twilio.type.PhoneNumber("(123) 456-7890"))
              .fetch();
        System.out.println(number.getPhoneNumber());
        System.out.println(number.getNationalFormat());
`

### Exception/Log
`
Exception in thread "main" com.twilio.exception.ApiException: The requested resource /PhoneNumbers/(123)456-7890 was not found
	at com.twilio.rest.lookups.v1.PhoneNumberFetcher.fetch(PhoneNumberFetcher.java:136)
	at com.twilio.rest.lookups.v1.PhoneNumberFetcher.fetch(PhoneNumberFetcher.java:25)
	at com.twilio.base.Fetcher.fetch(Fetcher.java:45)
	at com.binaryfountain.compass.twilio.TwilioMessageCreator.main(TwilioMessageCreator.java:106)
`

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by ugnich** [comment]
Same issue.

Phone number need to be URLEncode-d here:
https://github.com/twilio/twilio-java/blob/0aa5de36bc2b3b9d6ed861eaae7ebe0f227ba7af/src/main/java/com/twilio/rest/lookups/v1/PhoneNumberFetcher.java#L138

**Comment by childish-sambino** [comment]
@ugnich Yup, this is near the top of our backlog. Pull requests and +1s on the issue summary will help it move up the backlog.

Similar issue fixed recently in Ruby: https://github.com/twilio/twilio-ruby/pull/468
