### ISSUE TITLE
Incorrect use of java.net.URI for ICE servers

### ISSUE THREAD

**Issue by kohenkatz** [twilio/twilio-java#400]
**Version:** 7.17.0

In [`com.twilio.type.IceServer`](https://github.com/twilio/twilio-java/blob/73f8176cc55349ec246bd148ec8c0112e47fefdf/src/main/java/com/twilio/type/IceServer.java#L18), the `url` of the ICE server is returned as a `java.net.URI` object.

However, [RFC 7064 (URI Scheme for the Session Traversal Utilities for NAT (STUN) Protocol)](https://tools.ietf.org/html/rfc7064) Section 3.1 says:

> Developers MUST NOT use a generic hierarchical URI parser to parse a "stun" or "stuns" URI.

Likewise, [RFC 7065 (Traversal Using Relays around NAT (TURN) Uniform Resource Identifiers)](https://tools.ietf.org/html/rfc7064) Section 3.1 says:

> Developers MUST NOT use a generic hierarchical URI parser to parse a "turn" or "turns" URI.

Use of `java.net.URI` violates these requirements. The ICE server URI should properly be handled as a plain `String` or using a custom parser based on `java.net.URI`.

This bug presents itself in the following code example, which would work for a regular (say, `HTTP`, for example) URI:

```
URI stripQueryAndFragment(URI source) {
    return new URI(source.getScheme(), source.getAuthority(), source.getPath(), null, null);
}
```

For a STUN URI, this throws:

> ```
> java.net.URISyntaxException: Expected scheme-specific part at index 5: stun:
>        at java.net.URI$Parser.fail(URI.java:2848)
>        at java.net.URI$Parser.failExpecting(URI.java:2854)
>        at java.net.URI$Parser.parse(URI.java:3057)
>        at java.net.URI.<init>(URI.java:746)
>        at com.example.Utils.stripQueryAndFragment(Utils.java:47)
>```

**Comment by thinkingserious** [comment]
Hello @kohenkatz,

Thank you for reporting this! This bug has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by kohenkatz** [comment]
@thinkingserious Thanks.

Question if I want to do a PR - how should I handle backwards compatibility? Should I leave some of the `URI` stuff and mark it `@Deprecated`? Or should I just take it out and let it be a breaking change?
