### ISSUE TITLE
Remove joda-time dependency

### ISSUE THREAD

**Issue by ptahchiev** [twilio/twilio-java#409]
Can't you just use `java.time.LocalDateTime` instead? If you really need to use it, I suggest you mark the dependency as compile tome scope only and add some checks if the user has added joda-time in their classpath.

**Comment by codylerum** [comment]
I would be great if the next major release could drop java 7 support and move to java 8 and the standard java.time library

**Comment by codylerum** [comment]
Do you have any indication of how many users are still on Java 7 and if they are staying current with new releases? 

It would be great to move this up to Java 8 and eliminate the conversion between joda and standard JSR310 Date/Time for everyone on modern Java releases.

**Comment by thinkingserious** [comment]
Hello @ptahchiev,

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

@codylerum, @Cliabhach,

We will be evaluating support for older versions of Java soon, but unfortunately I don't have a concrete timeline for that.

With best regards,

Elmer

**Comment by codylerum** [comment]
@thinkingserious I took a look at doing a pull request for this last month, but considering everything is generated by Yoyodyne it seemed like it would be a wasted effort.

**Comment by childish-sambino** [comment]
@codylerum PRs are welcome, even if they only illustrate a partial (working) implementation. It can serve as a template for back-porting the changes into the code generator.

**Comment by codylerum** [comment]
@childish-sambino PR -> #503

**Comment by childish-sambino** [comment]
@codylerum I'm working on getting some Java 7 usage data and determining what the support model should be going forward. Won't be able to move forward with this until then.

**Comment by codylerum** [comment]
@childish-sambino No problem. I would be curious to know what percentage of users are on Java 7 AND are also actively keeping up with twilio-java releases.

I have not doubt there are still Java 7 users out there, but I would imagine most are applications that are stale and won't be updating the java version or twilio-java and just remain on an old twilio-java release until something changes to force their hand.

**Comment by childish-sambino** [comment]
@codylerum Yup, that's exactly the data we're looking at: how many java 7 users are using a version of this lib released since start of 2019.

**Comment by matejsp** [comment]
Based on https://www.baeldung.com/java-in-2019 there are 8% of java 7. But it adds up to more than 100% ... Well developers, that I can really feel sorry for, can still use backported jsr310 https://www.threeten.org/threetenbp/ ... please lets move to modern java

**Comment by childish-sambino** [comment]
FYI, as noted in the README, we'll be dropping support for Java 7 on 2020-10-01 and resolving this issue (after merging the changes, of course).
