### ISSUE TITLE
 access denied ("java.net.NetPermission" "getProxySelector")

### ISSUE THREAD

**Issue by balajigite16** [twilio/twilio-java#412]
in 
 Message message = Message.creator(to, from, messageStr).create();

**Comment by thinkingserious** [comment]
Hello @balajigite16,

This appears to be a code signing issue. Could you please provide a bit more information so that I may try to reproduce?

1. How did you install this helper library?
2. Please describe the server environment this code is being run on. 

Thank you!

With best regards,

Elmer
