### ISSUE TITLE
Cannot resolve messaging dependency in pants BUILD

### ISSUE THREAD

**Issue by fishercoder1534** [twilio/twilio-java#413]
I'm using pants as my BUILD automation tool, however, I cannot resolve the Twilio messaging depedency.

I'm following this [tutorial](https://www.twilio.com/docs/sms/services/api/phone-numbers)

However, I got:
![image](https://user-images.githubusercontent.com/20746576/40393151-2ce60db0-5dd3-11e8-9615-3994475bebc8.png)

Here's my BUILD file:
java_library(name='lib',
  sources=rglobs('*.java'),
  dependencies=[
'3rdparty:com.twilio.sdk.twilio',
]
)

How should I import/resolve this dependency issue?

Thanks!

**Comment by thinkingserious** [comment]
Hello @fishercoder1534,

According to [this documentation](https://github.com/twilio/twilio-java/issues/413), it looks like you will need a `jar_library` section.

Please take a look and let me know how it goes. Thank you!

With best regards,

Elmer
