### ISSUE TITLE
Delete Call log

### ISSUE THREAD

**Issue by AndreasRoed** [twilio/twilio-java#417]
Version: 7.17.7, 7.20.0, 7.21.3 & HTTP API

The Java SDK and HTTP API seem to not be able to delete the call logs even tough they both return true/204.

The Message.deleter works fine.

### Code Snippet
```
ResourceSet<Call> calls = Call.reader().setTo("phone_number").read();
for (Call call : calls) {
    boolean deleted = Call.deleter(call.getSid()).delete();
}
```
The call returns true, the API call returns 204, but the entries are still visible in the Twilio Console and can be fetched with the API.

### Steps to Reproduce
1. Fetch call logs for specific number
2. Delete logs with the Sid
3. Logs should be deleted, but are not

**Comment by thinkingserious** [comment]
Hello @AndreasRoed,

Thank you for reporting this issue and for your patience with our delayed response!

Are the entries still visible in your call logs? They should have been removed at 30 days.

With best regards,

Elmer
