### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by bohnman** [twilio/twilio-java#428]
Former title: lastRequest and lastResponse in HttpClient should be volatile

**Version:**

7.22.0

### Code Snippet
HttpClient.java
```java
private Response lastResponse;  // missing volatile
private Request lastRequest;  // missing volatile
```

### Steps to Reproduce
The lastRequest and lastResponse members in HttpClient should be volatile because the class is indirectly used as a singleton through TwilioRestClient in the Twilio class and therefore is subject to multiple threads.

**Comment by thinkingserious** [comment]
Great catch @bohnman!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Just a note that we should consider all the linked issues and come up with acceptance criteria to help this helper library become thread safe, then create the individual tickets needed to execute.

**Comment by alamothe** [comment]
`Twilio:: getRestClient` is also not thread-safe.

**Comment by bibinss** [comment]
@thinkingserious Is this issue up for dev/PR? if yes, I would like to pick it up

**Comment by childish-sambino** [comment]
@bibinss It's all yours!

**Comment by bibinss** [comment]
@thinkingserious I have put a comment on https://github.com/twilio/twilio-java/issues/429. would you mind taking a look?

**Comment by tomas-c** [comment]
> Pull requests and +1s on the issue summary will help it move up the backlog.

+1

**Comment by childish-sambino** [comment]
@tomas-c 
> on the issue summary

**Comment by sruthipusunuru** [comment]
Is this issue solved, is TwilioRestClient thread-safe?

**Comment by childish-sambino** [comment]
@sruthipusunuru No.

Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
If your app is multi-threaded _and_ dependent on accessing `lastRequest/lastResponse`, then it needs to not use `com.twilio.Twilio` which creates/uses a static singleton of `com.twilio.http.TwilioRestClient`. Instead, construct a new `TwilioRestClient` per thread as illustrated [here](https://github.com/twilio/twilio-java/#using-a-different-client).

Otherwise, `TwilioRestClient` is thread-safe.
