### ISSUE TITLE
Request and Response objects are not thread safe

### ISSUE THREAD

**Issue by bohnman** [twilio/twilio-java#429]
**Version:**

7.22.0

### Steps to Reproduce
The Request and Response objects are not thread safe.  They need to be because they are used as shared objects in HttpClient -> TwilioRestClient -> Twilio.

I would recommend making these objects immutable and any change (adding headers etc) would create a new request/response.  A builder pattern is great for this.

**Comment by thinkingserious** [comment]
Related to: https://github.com/twilio/twilio-java/issues/428

**Comment by bibinss** [comment]
@thinkingserious do you have some background on the need for
```private Response lastResponse;
    private Request lastRequest;``` in the HttpClient?
Looking at the usage I see both being used only in one unit test case to test `reliableRequest` method. So my point is if this added only for testing, we don't need to make the access methods `getLastResponse()` and `getLastRequest()` public - instead we can mark these as `visible for testing` and make them default access. That way we probably dont want to make `lastResponse` and `lastRequest` threadsafe.

But if we really need `lastResponse` and `lastRequest` to be part of the HttpClient, then as @bohnman  suggested, we need to make Response and Request immutable to make them threadsafe.

**Comment by childish-sambino** [comment]
@bibinss I'll follow up on #428 about this so we have a single-threaded conversation.
