### ISSUE TITLE
executor service never gets cleaned up

### ISSUE THREAD

**Issue by bohnman** [twilio/twilio-java#431]
**Version:**

7.22.0

### Code Snippet
```java
public static void main(String[] args) {
   Twilio.init("username", "password");
   Twilio.getExecutorService().submit(() -> System.out.println("Run"));
   Message.creator(new PhoneNumber("to"), new PhoneNumber("from"), "Testing.").create();
}
```

### Steps to Reproduce
1. Run the provided code
2. Notice how the jvm doesn't shut down

The JVM doesn't shut down because there is a thread left hanging around in the executor service.

I would recommend the following:

Add a new field: 
```java 
private static boolean selfCreatedExecutorService = false;
```

Modify setExecutorService:
```java
public synchronized void setExecutorService(ListeningExecutorService executorService) {
    ListeningExecutorService oldExecutorService = Twilio.executorService;
    Twilio.executorService = executorService;
    
    if (oldExecutorService != null && selfCreatedExecutorService) {
        oldExecutorService.shutdownNow();
    }

    selfCreatedExectorService = false;
}
```

Modify getExecutorService, adding the line right after the creation and assignment of the executor service and after applying multi-threading fixes as described in #430.

```java
selfCreatedExecutorService = true;
```

Add a destroy method:

```java
public static synchronized void destroy() {
    if (executorService != null && selfCreatedExecutorService) {
        executorService.shutdownNow();
    }
}
```

Add a shutdown hook:

```java
static {
   Runtime.getRuntime().addShutdownHook(new Thread(() -> Twilio.destroy()));
}
```

Finally, document that it is recommended to call Twilio.destroy before JVM shutdown.  However, the shutdown hook will take care of it as a fallback.

**Comment by bohnman** [comment]
email sent.  Thanks!

**Comment by thinkingserious** [comment]
Thanks @bohnman!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer
