### ISSUE TITLE
Request should consider Time Zone when adding DateTime Ranges

### ISSUE THREAD

**Issue by mfulgo** [twilio/twilio-java#432]
**Version:** 7.22.0
### Code Snippet
```java
Range<DateTime> atMost30sAgo = GuavaRange.atLeast(now().minusSeconds(30))
Message.reader().setDateSent(atMost30sAgo).read()
```

I believe the method of Request.java that sets `DateTime` query parameters should convert those objects to UTC before writing them to strings. 
[addQueryDateTimeRange](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/http/Request.java#L171) could become
```java
        if (range.hasLowerBound()) {
            String value = range.lowerEndpoint().withZone(UTC).toString(QUERY_STRING_DATE_TIME_FORMAT);
            addQueryParam(name + ">", value);
        }

        if (range.hasUpperBound()) {
            String value = range.upperEndpoint().withZone(UTC).toString(QUERY_STRING_DATE_TIME_FORMAT);
            addQueryParam(name + "<", value);
        }
```
Alternatively, it looks like the REST API supports putting the timezone on the parameter value. [The format string](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/http/Request.java#L25) could be
```java
    public static final String QUERY_STRING_DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSZ";
```

The following has been moved to: https://github.com/twilio/twilio-java/issues/501
I'd also suggest updating the JavaDoc to better indicate the API behavior: From what I've observed, it only cares about the Date part of the DateSent parameter. (Trying to get the last 30s of messages returns the full day's worth of messages.) I think making a note of that in the JavaDoc would help out new users.

**Comment by thinkingserious** [comment]
Thanks for taking the time to bring this issue to our attention @mfulgo!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
Fixed by https://github.com/twilio/twilio-java/pull/529
