### ISSUE TITLE
Is TwilioRestClient thread safe?

### ISSUE THREAD

**Issue by applegrew** [twilio/twilio-java#441]
Inside the code of `TwilioClient` I can see it creates new connection pool and httpclient. We see performance hit if we create `TwilioRestClient` for every request we want to make. Is it okay to create a single instance of `TwilioRestClient` and use it from multiple threads simultaneously?

**Comment by thinkingserious** [comment]
Hello @applegrew,

Thanks for taking the time to report this issue! 

Please follow [this issue](https://github.com/twilio/twilio-java/issues/428) for progress.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
@applegrew Please see the comment here: https://github.com/twilio/twilio-java/issues/428#issuecomment-697868934
