### ISSUE TITLE
Region support for de1

### ISSUE THREAD

**Issue by leonkay** [twilio/twilio-java#450]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
7.35

### Code Snippet
https://www.twilio.com/docs/libraries/reference/twilio-java/7.35.0/com/twilio/twiml/voice/Conference.Region.html

It looks like DE1 is not supported in your SDK though it appears on your documentation.
Can the SDK Conference.Region class be updated for this?

**Comment by spalmertwilio** [comment]
Closing as we have support in https://www.twilio.com/docs/libraries/reference/twilio-java/7.37.3/com/twilio/twiml/voice/Conference.Region.html
