### ISSUE TITLE
Shortened URLs linking to images have no spaces between them when a MMS with several images is converted to SMS

### ISSUE THREAD

**Issue by cynthux** [twilio/twilio-java#455]
Hi,

I'm trying to send a MMS with two images but when MMS is not supported and the images are converted to shortened URLs, there is no space between them. For example:

> This is my MMS converted to SMS https://m.twil.io/iFQQBEk7QVhttps://m.twil.io/DgkrgKNdZH

So, it is not possible to open the link because the browser in my phone tries to open the entire URL.

I didn't find any workaround.
Thanks in advance!

**Version:** 7.37.0

### Code Snippet
```java
twilioMessage = Message.creator(new PhoneNumber(phoneNumber), 
        MESSAGGING_SERVICE_SID, message)
        .setMediaUrl(urls.stream().map(URI::create).collect(Collectors.toList()))
	.create();
```
The same behaviour is seen when I try to send a cURL with two MediaUrl.

### Steps to Reproduce
1. Try to send a MMS with two images to a MMS-incompatible number or unsupported carrier.
2. Try to open the concatenated URL.

**Comment by thinkingserious** [comment]
Hello @cynthux,

Thanks for taking the time to report this!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
On second look, your code looks correct and this is not something that can be resolved in this library. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact).
