### ISSUE TITLE
java.lang.NoSuchFieldError: AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by khyatiChitroda** [twilio/twilio-java#474]
Original Title: java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier;

Hello sir,

I had implemented "com.twilio.sdk:twilio:7.41.1" for what's app api. 
```
 Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

  Message message = Message
                .creator(new PhoneNumber("+whatsapp:+9196######25"), new PhoneNumber("+whatsapp:+161######58"),
                        "Hi Joe! Your order D45987AB will arrive on 8/12/2018 before 8 pm.")
                .create();
        System.out.println(message.getSid());
```

It is Build properly and also I can run this but getting error while open the application:
```
error: ATAL EXCEPTION: main
    Process: com.sohel.twilioexample, PID: 28821
    java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
```

**Comment by thinkingserious** [comment]
Hello @khyatiChitroda,

Thanks for taking the time to report this issue!

Could you please provide some detail about how you installed this helper library and some details about your development environment so that I may try to reproduce?

With best regards,

Elmer

**Comment by khyatiChitroda** [comment]
PFA code in which I am getting error message.
 Twiliodemo.zip
<https://drive.google.com/file/d/14Txdplu_Y2RmWHHBuIe99wktdceltQG_/view?usp=drive_web>

**Comment by childish-sambino** [comment]
This looks like a mobile android app, but the twilio-java library is not intended for client/browser-side use as it required API credentials to interact with the Twilio API. Recommend moving Twilio API usage to back-end server.
