### ISSUE TITLE
"speechModel"  attribute is missing from the Gather class

### ISSUE THREAD

**Issue by AlexeyStadnik** [twilio/twilio-java#488]
### Feature Request
The "speechModel" attribute (https://www.twilio.com/docs/voice/twiml/gather#speechmodel) is missing from the Gather verb (https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/twiml/voice/Gather.java) in java SDK.

### Current Gather attributes supported in java SDK 
```java
    private final List<Gather.Input> input;
    private final URI action;
    private final HttpMethod method;
    private final Integer timeout;
    private final String speechTimeout;
    private final Integer maxSpeechTime;
    private final Boolean profanityFilter;
    private final String finishOnKey;
    private final Integer numDigits;
    private final URI partialResultCallback;
    private final HttpMethod partialResultCallbackMethod;
    private final Gather.Language language;
    private final String hints;
    private final Boolean bargeIn;
    private final Boolean debug;
    private final Boolean actionOnEmptyResult;
```
 Could support for this be added? Thanks.

**Comment by AlexeyStadnik** [comment]
Fix typos

**Comment by childish-sambino** [comment]
Similar issue: https://github.com/twilio/twilio-csharp/issues/477

**Comment by childish-sambino** [comment]
I've bumped the internal team to get this fixed. It's generated code so changes are needed upstream.

**Comment by childish-sambino** [comment]
Added as part of the [7.47.2](https://github.com/twilio/twilio-java/releases/tag/7.47.2) release.
