### ISSUE TITLE
Update the JavaDoc to better indicate API behavior

### ISSUE THREAD

**Issue by thinkingserious** [twilio/twilio-java#501]
From issue #432:

> I'd also suggest updating the JavaDoc to better indicate the API behavior: From what I've observed, it only cares about the Date part of the DateSent parameter. (Trying to get the last 30s of messages returns the full day's worth of messages.) I think making a note of that in the JavaDoc would help out new users.

Acceptance Criteria:
1. Reproduce the above behavior
2. Update the JavaDoc accordingly

**Comment by childish-sambino** [comment]
This requires updates to the upstream API definition. Recommend [filing a support ticket](https://twilio.com/help/contact) to look into this.
