### ISSUE TITLE
SDK brings in outdated jjwt dependency

### ISSUE THREAD

**Issue by JessePreiner** [twilio/twilio-java#505]
We were experiencing various NoSuchMethod exceptions while trying to parse jwt tokens. Turned out the issue started when we brought in the twilio java sdk. It has a transitive dependency on an outdated version of jjwt (0.4, now at 0.9.1). There are various work-arounds (we ended up adding an exclusion for jjwt in the twilio dependency) but it seems like upgrading from jjwt 0.4 -> jjwt 0.9.1 would be feasible.

**Version:**
twilio java sdk 7.42.0

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by saksham93** [comment]
Raised a PR #508 to close this issue.
