### ISSUE TITLE
Easy way to use NetworkHttpClient with custom connection and socket timeouts 

### ISSUE THREAD

**Issue by eguimerans** [twilio/twilio-java#513]
### Issue Summary
Connection and Socket timeout values when using default Twilio httpClient implementation are hardcoded, therefore there is no an easy option to customized them but create your complete own HttpClient object. A constructor accepting **RequestConfig** object parameters would help for this; Or making _private_ members _protected_ so the class can be easily extended and values overriden...

### Steps to Reproduce
Try to create a TwilioRestClient object with custom timeouts for requests; ideally should be good to have an option to customize somehow the existing **NetworkHttpClient** object

### Code Snippet
```java
public class NetworkHttpClient extends HttpClient {

    private static final int CONNECTION_TIMEOUT = 10000;
    private static final int SOCKET_TIMEOUT = 30500;

    private final org.apache.http.client.HttpClient client;

    /**
     * Create a new HTTP Client.
     */
    public NetworkHttpClient() {
        RequestConfig config = RequestConfig.custom()
            .setConnectTimeout(CONNECTION_TIMEOUT)
            .setSocketTimeout(SOCKET_TIMEOUT)
            .build();
...
```

### Technical details:
* twilio-java version: 7.47.3
* java version: 8

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by eshanholtz** [comment]
The fix will be included in the next release scheduled for 04/15/2020
