### ISSUE TITLE
Chinese language are not supported in the Call API (TwiML)

### ISSUE THREAD

**Issue by frannnnk** [twilio/twilio-java#515]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```java
 Call call = Call.creator(
                new PhoneNumber("+85250000000"),
                new PhoneNumber("+16602092666"),
                new com.twilio.type.Twiml("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Response><Say language=\"zh-HK\" voice=\"alice\">希望在好快嘅將來可以見到大家。祝大家新年快樂。</Say></Response>")).create();
```

### Exception/Log
It said "Sorry, an application error has occurred." in the call.
```
Error on line 1 of document : XML document structures must start and end within the same entity. 
```
and in the debug page can see the xml received is garbled:
```
<?xml version="1.0" encoding="UTF-8"?><Response><Say language="zh-HK" voice="alice">���������������������������������������������������
```

### Technical details:
* twilio-java version: 7.47.4
* java version: 11

**Comment by childish-sambino** [comment]
Best to open a [support ticket](https://twilio.com/help/contact) as I don't think this is something that can be solved in the Java library.
