### ISSUE TITLE
Add examples of how to get phone numbers in a specific country, or TollFree/Local 

### ISSUE THREAD

**Issue by kevinburke** [twilio/twilio-java#58]
The example only exposes getAvailablePhoneNumbers()

**Comment by MikeGratsas** [comment]
In SDK version 6 there was method  public AvailablePhoneNumberList Account.getAvailablePhoneNumbers(Map<String, String> filters, String isoCountry, String type). However, in SDK version 7 classes Local, Mobile, TollFree  in availablephonenumbercountry package contain many common fields, but there is no superclass to process them identically indicating the type only
