### ISSUE TITLE
FaxReader has bug formatting ZoneDateTime to REST interface

### ISSUE THREAD

**Issue by noledgy** [twilio/twilio-java#592]
### Issue Summary
When calling FaxReader.read(client), it fails if you set setDateCreatedAfter() and/or setDateCreatedOnOrBefore(). Internally, when these dates are converted to a string, it is calling "toString()", which does not format in the form the Fax REST API requires, which is "setDateCreatedOnOrBefore". A DateTimeFormatter must be used to generate the string. I have made the correction and I am filing a pull request.

### Steps to Reproduce
Just try making  FaxReader.read(client) call, setting setDateCreatedAfter() or setDateCreatedOnOrBefore(). The call will throw an exception.

### Technical details:
* twilio-java version: 8.0.0
* java version: 1.8

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
