### ISSUE TITLE
setIfMachine() method and upgrade to 7.55.3 / 8.x

### ISSUE THREAD

**Issue by sryze** [twilio/twilio-java#599]
`CallCreator.setIfMachine(true/false)` was removed at some point in the 7.x branch but the [upgrade guide](https://github.com/twilio/twilio-java/blob/210d53181d541bc8fb61219d882bdc1c6b6fee39/UPGRADE.md) does not mention it, so I'm wondering what is the equivalent method in the new SDK?

Should I replace:

```
callCreator.setIfMachine("Hangup");
```

with:

```
callCreator.setMachineDetection("Enable");
```

?

**Comment by thinkingserious** [comment]
Hello @sryze,

Yes, your replacement code looks correct to me. Those types of updates are generally tracked [here](https://github.com/twilio/twilio-java/releases).

[Here](https://stackoverflow.com/questions/43219096/twilio-ifmachine-rest-code) is some further context and here are the [latest docs](https://www.twilio.com/docs/voice/answering-machine-detection#machinedetection).

Thank you for reaching out!

With best regards,

Elmer
