### ISSUE TITLE
Example mock or sample test

### ISSUE THREAD

**Issue by amir20001** [twilio/twilio-java#600]
### Issue Summary
I would love to see some examples of how to mock the RestClient or even better a pre-built test helper, I personally can not figure out how to handle this and I'm finding myself digging into the details of the lib to figure out how to test it.

I would love to see an example where a call to Twilio can be faked a someway to assert the values that are sent.

This is what I have come up with, but does not work since the message creator calls the rest service.

```

public class SmsServiceTest {

    private SmsService smsService;
    private ObjectMapper objectMapper;

    @Before
    public void setUp() throws Exception {
        final TwilioRestClient mockClient = mock(TwilioRestClient.class);
        objectMapper = new ObjectMapper();
        smsService = new SmsService(mockClient);

        final Message message = Message.creator(new PhoneNumber("+11231231234"), new PhoneNumber("+11231231234), "hellp")
            .create(mockClient);
        when(mockClient.request(any())).thenReturn(new Response(objectMapper.writeValueAsString(message), 200));
    }

    @Test
    public void example() {
        smsService.sendMessage("+11231231234", "asdasdasd");
    }
}
```

**Comment by eshanholtz** [comment]
Hi @amir20001 

You can see an examples of how we mock the `TwilioRestClient` in our integration tests. [Here's the one for our Message resource](https://github.com/twilio/twilio-java/blob/main/src/test/java/com/twilio/rest/api/v2010/account/MessageTest.java). We use the [`jmockit`](https://github.com/twilio/twilio-java/blob/main/pom.xml#L218) package for mocking.
