### ISSUE TITLE
Require to use Username

### ISSUE THREAD

**Issue by 09905x0** [twilio/twilio-java#605]
### Issue Summary
Doc example asking for **Username**

### Steps to Reproduce
Just run the example: https://www.twilio.com/docs/lookup/quickstart

### Code Snippet
```java
import com.twilio.Twilio;
import com.twilio.rest.lookups.v1.PhoneNumber;

public class Example {
  // Find your Account Sid and Token at twilio.com/console
  // and set the environment variables. See http://twil.io/secure
  public static final String ACCOUNT_SID = System.getenv("--");
  public static final String AUTH_TOKEN = System.getenv("--");

  public static void main(String[] args) {
    Twilio.init(ACCOUNT_SID, AUTH_TOKEN);
    PhoneNumber phoneNumber =
        PhoneNumber.fetcher(new com.twilio.type.PhoneNumber("+447931986318"))
            .setCountryCode("US")
            .fetch();

    System.out.println(phoneNumber.getCallerName());
  }
}

```

### Exception/Log
```
# paste exception/log here
Exception in thread "main" com.twilio.exception.AuthenticationException: Username can not be null
	at com.twilio.Twilio.setUsername(Twilio.java:81)
	at com.twilio.Twilio.init(Twilio.java:56)
	at Example.main(Example.java:13)
```

### Technical details:
* twilio-java version: 8.3.0
* java version: 8

**Comment by JenniferMah** [comment]
@09905x0 
This looks like an issue with your Twilio credentials. When initializing  your `ACCOUNT_SID ` and `AUTH_TOKEN`, make sure these are stored securely by using environment variables. Please checkout our [documentation](http://twil.io/secure) on how to store Twilio credentials securely. Don't forget to source the file you stored your credentials in before running your script.

**Comment by 09905x0** [comment]
Hey, @JenniferMah thanks for taking out of your time to respond.
