### ISSUE TITLE
Partial attribute update on Workers

### ISSUE THREAD

**Issue by dinchand** [twilio/twilio-java#612]
### Issue Summary
This is a feature request/ query . We make dynamic updates to worker attributes several times a day. However we only need to update one attribute in the entire json, but currently need to set the entire attribute json every time. Is it possible to add a method to the WorkerUpdater to do a partial attribute update ?

**Comment by thinkingserious** [comment]
Hello @dinchand,

I'm not quite sure how your workflow is executed. Do you have sample code you can share to help clarify? Meanwhile, perhaps [this endpoint](https://sendgrid.api-docs.io/v3.0/transactional-templates/edit-a-transactional-template) may be what you need.

With best regards,

Elmer

**Comment by dinchand** [comment]
We have a use case where one of the Taskrouter worker attribute changes quite frequently. E.g.
Worker has following attributes
```json
{
"routing":{
   "skills":["Private","Mortgages","Lending"],
   "languages":["NL","FR"],
   "channels":["Chat","Video"]},
"availability":"general"
}
```

Now we have frequent updates to only the  **availability** field. But the `WorkerUpdater.setAttributes`. takes the entire json for the update. Is it possible to have a PATCH instead of POST for such requests?

**Comment by shwetha-manvinkurke** [comment]
@dinchand Sounds like a valid feature request but this is beyond the scope of our library. Please reach out to [support](https://support.twilio.com/) with the request.
