### ISSUE TITLE
How to create an AccessToken for subaccount?

### ISSUE THREAD

**Issue by verboomp** [twilio/twilio-java#614]
### Issue Summary

This is probably more a question as an issue but I am unable to get video room working with a subaccount.
I am streaming from one device (iPad) to another device (browser). This all works well when I use the main Twilio account with the SID, account key and account secret. The billing in the Twilio backend shows the amount I have used. I am however unable to stream with a subacount and have the billing in the Twilio backend for this subaccount. 
The AccessToken that is turned into a JWT String works fine with the main account but doesn't work with a subaccount SID or I am generating the JWT wrong for the subaccount:

For the main account I use:

`
final AccessToken token = new AccessToken.Builder(
System.getProperty("TWILIO_ACCOUNT_SID"),
System.getProperty("TWILIO_API_KEY"),
System.getProperty("TWILIO_API_SECRET"))
.identity(identity).grant(grant).build();

return token.toJwt();
`
The subaccount doesn't have a new API key and secret so I assume they stay the same and I only need to change the accountSID with that from the subaccount. When I do that than I get 
`Code=20151 "The authorization with Token failed"`
I have looked in the Twilio backend but I am unable to find new subaccount API key and secret. The only other thing I can find is the AUTH TOKEN but since I don't use the AUTH token from the main account I assume I don't need that for a subaccount either. ( I have tried experimenting with it but that didn't work either). 

Can somebody please give me a clue on what I do wrong and how I can get this working?

Kind regards, 
Patrick

### Technical details:
* twilio-java version:  8.1.0
* java version: 11

**Comment by thinkingserious** [comment]
Hello @verboomp,

Thank you for taking the time to report this!

In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact). Thanks!

With best regards,

Elmer
