### ISSUE TITLE
Remove Lombok

### ISSUE THREAD

**Issue by aSemy** [twilio/twilio-java#646]
### Issue Summary

At the moment this project depends on Lombok

https://github.com/twilio/twilio-java/blob/0e4637bb772209737e3a689665b8a07cd99b3d58/pom.xml#L139

Lombok is mostly used for basic functionality, usually adding default `toString()` methods. These can be auto generated instead, and so a dependency on Lombok adds overhead to this project. 

Because Lombok generates the code behind the scenes, it's not easily possible to tell if the code Lombok generates is even necessary.

Additionally because Lombok edits the code during compilation this means other tools that do post processing (documentation generators, optimisation and analysis tools, etc) are much more difficult, if not impossible, to use. 

Please remove Lombok from the project.

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
I disagree that Lombok is not beneficial. It reduces the amount of code needed to be maintained. Post-processing tools should work off the delomboked source.
