### ISSUE TITLE
Can't find v8.24.0 in Maven

### ISSUE THREAD

**Issue by dcanonmolina** [twilio/twilio-java#664]
Hello!
I was trying to add the latest Java SDK version v8.24.0 but Maven returned: 

> Not Found: /artifact/com.twilio.sdk/twilio/8.24.0

Is it available there?

**Comment by JenniferMah** [comment]
Hi @dcanonmolina! The Java SDK version v8.24.0 should now be available on Maven [here](https://mvnrepository.com/artifact/com.twilio.sdk/twilio).
