### ISSUE TITLE
Missing category: channels-whatsapp-outbound in Twilio-java SDK

### ISSUE THREAD

**Issue by Krishnanudhaya** [twilio/twilio-java#703]
I couldn't find the category channels-whatsapp-outbound in Twilio-java SDK to get the usage records. 

We could achieve the same using the rest endpoint provided in documentation ( https://www.twilio.com/docs/usage/api/usage-record )
Rest end point : https://api.twilio.com/2010-04-01/Accounts/{{TWILIO_ACCOUNT_SID}}/Usage/Records.json?Category=channels-whatsapp-outbound&StartDate=2022-03-01&EndDate=2022-06-30&PageSize=20

But, same category is not available in Twilio Java SDK. 

- com.twilio.rest.api.v2010.account.usage.Record
- class name : Record.java
- missing category : channels-whatsapp-outbound in Category (enum)

Can you advise how to pull the whats app usage records using Twilio Java SDK ?

![image](https://user-images.githubusercontent.com/50961924/180783573-fda38d21-3d20-41c9-998c-f84e1944db8a.png)

Thanks

**Comment by childish-sambino** [comment]
For some reason, these categories are not listed internally as valid options so this library is not generated to provide them. Recommend [filing a support ticket](https://twilio.com/help/contact) to inquire about adding this feature to the public API definitions.
