### ISSUE TITLE
Test Failures on NonDex

### ISSUE THREAD

**Issue by priyanka-28** [twilio/twilio-java#724]
### Issue Summary
The test com.twilio.jwt.taskrouter.PolicyTest#testToJson passed using normal maven-test, but showed Non-deterministic behavior under NonDex(https://github.com/TestingResearchIllinois/NonDex) and thus failed.

### Steps to Reproduce
https://github.com/TestingResearchIllinois/NonDex
Nondex is order-dependent flaky tests detection tool developed by a research group led professor Darko at UIUC
Navigate to the project repo, compile and run the following -

mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex

### Code Snippet
```java
# paste code here
```

### Exception/Log
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/52324780/206897492-6e8142cf-6343-4262-997c-507bd2138611.png">

### Technical details:
* twilio-java version: 9.1.4
* java version: 11.0.16.1

**Comment by rakatyal** [comment]
Hi @priyanka-28, thank you for reporting the issue and contributing to the fix! Please let us know of any issues.

**Comment by kridai** [comment]
HI @priyanka-28, your changes for the fix have been merged and should be available in the next release.
