### ISSUE TITLE
Can't find audio stream, microphone isn't recording on any devices.

### ISSUE THREAD

**Issue by muzammil-git** [twilio/twilio-java#762]
### Issue Summary
Where can I find the microphone audio stream,

When talking on a call from a Twilio number to a regular number, my microphone isn't working in any of the phones. Can you help me find where mic stream is coming from, can I tweak with it ?

**Comment by sbansla** [comment]
@muzammil-git
I believe the support team can assist you with that. I don't think this issue is related to the SDK, but please correct me if I'm wrong.

**Comment by sbansla** [comment]
Closing issue, No response.
