### ISSUE TITLE
messagingServiceSid can not send mediaUrl

### ISSUE THREAD

**Issue by Flappybay** [twilio/twilio-java#763]
### Issue Summary
Why can not send  picture when I use `messagingServiceSid ` to send SMS and use `PhoneNumber` is ok ?

### Code Snippet
```java
Message.creator(new PhoneNumber(receiptNumber), messagingServiceSid, content)
.setMediaUrl(imgUriList).create() // is failed
Message.creator(new PhoneNumber(receiptNumber), new PhoneNumber(from), content)
  .setMediaUrl(imgUriList).create(); // is success
```

### Technical details:
* twilio-java version:  7.38.1
* java version: 1.8

**Comment by sbansla** [comment]
Hi @Flappybay 
I am able to send message with image using messagingServiceSid
Message.creator(new PhoneNumber(receiptNumber), messagingServiceSid, content)
                .setMediaUrl(uris).create();
Note:
Environment: 9.6.1 twilio version

**Comment by sbansla** [comment]
Closing the issue as it was waiting for feedback
