### ISSUE TITLE
Implement a Twilio-specific runtime exception

### ISSUE THREAD

**Issue by alexcchan** [twilio/twilio-java#94]
There are places in code like this:

https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/sdk/TwilioRestClient.java#L428

where checked exceptions are wrapped in generic RuntimeException.

If instead these were wrapped in e.g. a TwilioRestRuntimeException this would allow code calling the API to catching these exceptions instead of having to catch RuntimeException.

http://forum.twilio.com/twilio/topics/please_fix_your_java_libraries_to_correctly_use_checked_exceptions

**Comment by jingming** [comment]
We have introduced a new suite of exceptions in `7.0.0` to avoid having to throw `RuntimeExceptions`.
